import type { CatalogItem } from "@/types/catalog";

const PH = "https://images.unsplash.com/photo-1631545806609-95f3e1b3eba1?w=1600&q=80&auto=format&fit=crop";
const PH_INDOOR = "https://images.unsplash.com/photo-1567769541495-138e4ddf08fc?w=1600&q=80&auto=format&fit=crop";
const PH_VILLA = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80&auto=format&fit=crop";
const PH_LUXURY = "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80&auto=format&fit=crop";

/** Visuels TRANE — `/public/img/products/trane/` (synchronisés depuis le build frontend). */
const TRANE_SPLIT_STANDARD_IMAGES = {
  packshot: "/img/products/trane/trane-split-mural-packshot.jpg",
  moroccoCasablanca: "/img/products/trane/trane-split-morocco-modern.jpg",
  moroccoRiad: "/img/products/trane/trane-split-morocco-riad.jpg",
} as const;

const TRANE_BLACK_MIRROR_IMAGES = {
  hero: "/img/products/trane/trane-black-mirror-hero.jpg",
  detail: "/img/products/trane/trane-black-mirror-detail.jpg",
} as const;

const TRANE_GAINABLE_IMAGES = {
  hero: "/img/products/trane/trane-gainable-hero.jpg",
  grille: "/img/products/trane/trane-gainable-grille.jpg",
} as const;

const TRANE_CASSETTE_IMAGES = {
  hero: "/img/products/trane/trane-cassette-hero.jpg",
  office: "/img/products/trane/trane-cassette-office.jpg",
} as const;

const TRANE_MULTISPLIT_IMAGES = {
  hero: "/img/products/trane/trane-multisplit-hero.jpg",
} as const;

const TRANE_VRF_IMAGES = {
  hero: "/img/products/trane/trane-vrf-hero.jpg",
} as const;

const TRANE_RENTAL_IMAGES = {
  hero: "/img/products/trane/trane-rental-hero.jpg",
} as const;

const TRANE_MOBILE_IMAGES = {
  hero: "/img/products/trane/trane-mobile-hero.jpg",
  lifestyle: "/img/products/trane/trane-mobile-morocco-lifestyle.jpg",
  studio: "/img/products/trane/trane-mobile-studio-detail.jpg",
} as const;

/** Visuels MEGALIFE / INGELEC — fichiers dans public/img/products/ (photos générées + studio). */
const MEGALIFE_IMAGES = {
  gainableOutdoor: "/img/products/megalife/gainable-outdoor-r410a-studio.jpg",
  gainableIndoor: "/img/products/megalife/gainable-indoor-studio.jpg",
  gainableOutdoorAlt: "/img/products/megalife/gainable-outdoor-inverter-studio.jpg",
  cassette: "/img/products/megalife/cassette-plafond-bureau.jpg",
  cassetteAlt: "/img/products/megalife/cassette-600-studio.jpg",
  biSplit: "/img/products/megalife/bi-split-versaty-lifestyle.jpg",
  biSplitAlt: "/img/products/megalife/bi-split-versaty-kit.jpg",
  biSplitCreative: "/img/products/megalife/bi-split-jsmart-21k-lifestyle.jpg",
  mobile: "/img/products/ingelec/ingelec-mobile-lifestyle.webp",
  mobileHero: "/img/products/ingelec/ingelec-mobile-hero.webp",
} as const;

const INGELEC_IMAGES = {
  muralInverter: "/img/products/ingelec/mural-inverter-hero.webp",
  muralInverterGallery: "/img/products/ingelec/mural-inverter-gallery-hero.webp",
  muralOnOff: "/img/products/ingelec/mural-onoff-hero.webp",
  muralOnOffSystem: "/img/products/ingelec/mural-onoff-system-hero.webp",
  cassette: "/img/products/ingelec/cassette-inverter-indoor-hero.webp",
  cassetteKit: "/img/products/ingelec/cassette-inverter-kit-hero.webp",
  gainable: "/img/products/ingelec/gainable-inverter-indoor-hero.webp",
  gainableKit: "/img/products/ingelec/gainable-inverter-kit-hero.webp",
  multiSplit: "/img/products/ingelec/ingelec-multi-split-villa-hero.webp",
  mobile: "/img/products/ingelec/ingelec-mobile-hero.webp",
  mobileLifestyle: "/img/products/ingelec/ingelec-mobile-lifestyle.webp",
  mobileDetail: "/img/products/ingelec/ingelec-mobile-detail.webp",
} as const;

/** Visuels LG — fichiers dans public/img/products/lg/ */
const LG_IMAGES = {
  artcoolMirror: "/img/products/lg/lg-artcool-mirror-hero.jpg",
  artcoolMirror2: "/img/products/lg/lg-artcool-mirror-2.jpg",
  artcoolMirror3: "/img/products/lg/lg-artcool-mirror-3.jpg",
  artcoolGallery: "/img/products/lg/lg-artcool-gallery-hero.webp",
  artcoolGallery2: "/img/products/lg/lg-artcool-gallery-2.webp",
  artcoolGallery3: "/img/products/lg/lg-artcool-gallery-3.webp",
  dualcool: "/img/products/lg/lg-dualcool-premium-hero.webp",
  dualcool2: "/img/products/lg/lg-dualcool-premium-2.webp",
  dualcool3: "/img/products/lg/lg-dualcool-premium-3.webp",
  multiSplit: "/img/products/lg/lg-multi-split-hero-exterior-view.jpg",
  multiSplitInterior: "/img/products/lg/lg-multi-split-gallery-2-morocco-interior.jpg",
  multiSplitKitchen: "/img/products/lg/lg-multi-split-gallery-3-morocco-kitchen-cassette.jpg",
  multiV5: "/img/products/lg/lg-multi-v-5-hero-essaouira.jpg",
  multiV52: "/img/products/lg/lg-multi-v-5-2.webp",
  multiV53: "/img/products/lg/lg-multi-v-5-3.webp",
  cassetteGainable: "/img/products/lg/lg-cassette-gainable-hero.jpg",
  cassetteGainable2: "/img/products/lg/lg-cassette-gainable-2.webp",
  cassetteGainable3: "/img/products/lg/lg-cassette-gainable-3.webp",
  mobile: "/img/products/lg/lg-mobile-morocco-hero.jpg",
  mobile2: "/img/products/lg/lg-mobile-morocco-2.jpg",
  mobile3: "/img/products/lg/lg-mobile-morocco-3.jpg",
} as const;

export const climatisationItems: CatalogItem[] = [
  // ========== MEGALIFE ==========
  // ---- MEGALIFE ENCASTRABLE — Catalogue officiel 2026 ----
  {
    id: "megalife-gainable-inverter-r410a",
    category: "climatisation",
    brand: "MEGALIFE",
    name: "Climatiseur Gainable Inverter R410A",
    gammeLabel: "Encastrable Gainable — Inverter R410A",
    shortDescFr:
      "Gainable MEGALIFE Inverter R410A — intégration faux-plafond, distribution silencieuse par gaines. 4 puissances de 12 000 à 36 000 BTU/h en 220 V (hors 48 / 60 k).",
    longDescFr:
      "La gamme Gainable Inverter R410A MEGALIFE est conçue pour les villas modernes et bureaux haut de gamme du Maroc. Compresseur Inverter à modulation continue (économies d'énergie significatives), réfrigérant R410A, distribution discrète par réseau de gaines (seules les grilles sont visibles), pression statique ajustable, télécommande filaire incluse, Wi-Fi en option. Idéal pour conserver une esthétique épurée tout en climatisant uniformément plusieurs pièces.",
    image: MEGALIFE_IMAGES.gainableOutdoor,
    gallery: [
      MEGALIFE_IMAGES.gainableIndoor,
      MEGALIFE_IMAGES.gainableOutdoor,
      MEGALIFE_IMAGES.gainableOutdoorAlt,
    ],
    formats: ["Encastrable", "Gainable"],
    capacities: [
      "12 000 BTU/h Gainable Inverter — 220 V",
      "18 000 BTU/h Gainable Inverter — 220 V",
      "24 000 BTU/h Gainable Inverter — 220 V",
      "36 000 BTU/h Gainable Inverter — 220 V",
    ],
    variants: [
      {
        id: "megalife-gainable-r410a-36k",
        title: "36 000 BTU/h Gainable Inverter — 220 V",
      },
      {
        id: "megalife-gainable-r410a-24k",
        title: "24 000 BTU/h Gainable Inverter — 220 V",
      },
      {
        id: "megalife-gainable-r410a-18k",
        title: "18 000 BTU/h Gainable Inverter — 220 V",
      },
      {
        id: "megalife-gainable-r410a-12k",
        title: "12 000 BTU/h Gainable Inverter — 220 V",
      },
    ],
    specs: [
      { label: "Type", value: "Gainable basse pression" },
      { label: "Technologie", value: "Inverter DC" },
      { label: "Réfrigérant", value: "R410A" },
      { label: "Tension", value: "220 V" },
      { label: "Pression statique", value: "Réglable" },
      { label: "Contrôle", value: "Filaire fourni · Wi-Fi en option" },
      { label: "Garantie", value: "Constructeur MEGALIFE" },
    ],
    highlights: [
      "Inverter R410A — économies d'énergie",
      "Intégration totalement invisible",
      "4 capacités 12 000 → 36 000 BTU/h",
    ],
    crossSell: [
      "megalife-gainable-inverter-r32",
      "megalife-cassette-inverter",
      "contrat-entretien-annuel",
    ],
    badge: "Encastrable",
  },
  {
    id: "megalife-gainable-r410a",
    category: "climatisation",
    brand: "MEGALIFE",
    name: "Climatiseur Gainable R410A",
    gammeLabel: "Encastrable Gainable — On/Off R410A",
    shortDescFr:
      "Gainable MEGALIFE R410A en version On/Off — robuste et économique. 5 capacités, dont une 48 000 BTU/h en 380 V triphasé pour grandes villas.",
    longDescFr:
      "La gamme Gainable R410A MEGALIFE offre la fiabilité d'un compresseur On/Off éprouvé, idéal pour les rénovations à budget maîtrisé et les locaux à usage intermittent (résidences secondaires, locations touristiques). Distribution par gaines, pression statique ajustable, contrôle filaire. La version 48 000 BTU/h triphasée 380 V couvre les grands volumes (suites parentales, doubles salons).",
    image: MEGALIFE_IMAGES.gainableOutdoor,
    gallery: [MEGALIFE_IMAGES.gainableIndoor],
    formats: ["Encastrable", "Gainable"],
    capacities: [
      "12 000 BTU/h Gainable R410A — 220 V",
      "18 000 BTU/h Gainable R410A — 220 V",
      "24 000 BTU/h Gainable R410A — 220 V",
      "36 000 BTU/h Gainable R410A — 220 V",
      "48 000 BTU/h Gainable R410A — 380 V",
    ],
    specs: [
      { label: "Type", value: "Gainable basse pression" },
      { label: "Technologie", value: "On/Off (compresseur fixe)" },
      { label: "Réfrigérant", value: "R410A" },
      { label: "Tensions", value: "220 V (jusqu'à 36 k) · 380 V triphasé (48 k)" },
      { label: "Contrôle", value: "Filaire fourni" },
      { label: "Garantie", value: "Constructeur MEGALIFE" },
    ],
    highlights: [
      "5 capacités jusqu'à 48 000 BTU/h",
      "Triphasé 380 V disponible",
      "Solution accessible et robuste",
    ],
    crossSell: [
      "megalife-gainable-inverter-r410a",
      "megalife-gainable-inverter-r32",
      "contrat-entretien-annuel",
    ],
  },
  {
    id: "megalife-gainable-inverter-r32",
    category: "climatisation",
    brand: "MEGALIFE",
    name: "Climatiseur Gainable Inverter R32",
    gammeLabel: "Encastrable Gainable — Inverter R32 nouvelle génération",
    shortDescFr:
      "Le top de la gamme MEGALIFE encastrable : Inverter, gaz écologique R32, 6 capacités de 12 000 à 42 000 BTU/h, parfait pour villas haut de gamme.",
    longDescFr:
      "La gamme Gainable Inverter R32 MEGALIFE incarne la dernière génération de la marque : Inverter DC dernière génération, gaz écologique R32 (faible PRG), efficacité énergétique optimale (A++), réduction de bruit avancée. Distribution par gaines, pression statique réglable, télécommande filaire premium, compatible Wi-Fi. La référence pour les villas neuves recherchant performance et éco-responsabilité.",
    image: MEGALIFE_IMAGES.gainableIndoor,
    gallery: [MEGALIFE_IMAGES.gainableOutdoor],
    formats: ["Encastrable", "Gainable"],
    capacities: [
      "12 000 BTU/h Gainable Inverter R32 — 220 V",
      "18 000 BTU/h Gainable Inverter R32 — 220 V",
      "24 000 BTU/h Gainable Inverter R32 — 220 V",
      "30 000 BTU/h Gainable Inverter R32 — 220 V",
      "36 000 BTU/h Gainable Inverter R32 — 220 V",
      "42 000 BTU/h Gainable Inverter R32 — 220 V",
    ],
    specs: [
      { label: "Type", value: "Gainable basse pression" },
      { label: "Technologie", value: "Inverter DC nouvelle génération" },
      { label: "Réfrigérant", value: "R32 (écologique)" },
      { label: "Classe énergétique", value: "A++" },
      { label: "Tension", value: "220 V" },
      { label: "Contrôle", value: "Filaire premium · Wi-Fi en option" },
      { label: "Garantie", value: "Constructeur MEGALIFE" },
    ],
    highlights: [
      "Gaz R32 écologique",
      "Inverter DC nouvelle génération",
      "6 capacités 12 000 → 42 000 BTU/h",
    ],
    crossSell: [
      "megalife-cassette-inverter",
      "megalife-gainable-inverter-r410a",
      "contrat-entretien-annuel",
    ],
    badge: "Premium R32",
  },
  {
    id: "megalife-cassette-inverter",
    category: "climatisation",
    brand: "MEGALIFE",
    name: "Climatiseur Cassette Inverter",
    gammeLabel: "Encastrable Cassette 4 voies — Inverter",
    shortDescFr:
      "Cassette plafonnière 4 voies MEGALIFE en version Inverter — diffusion 360° pour grands salons et open-spaces.",
    longDescFr:
      "La gamme Cassette Inverter MEGALIFE s'encastre dans les faux-plafonds 600 × 600 mm et diffuse l'air sur 360° pour un confort homogène — idéale grands salons, suites parentales et open-spaces. Compresseur Inverter, pompe de relevage intégrée, télécommande filaire, redémarrage automatique, mode silencieux nocturne.",
    image: MEGALIFE_IMAGES.cassette,
    gallery: [MEGALIFE_IMAGES.cassette, MEGALIFE_IMAGES.gainableOutdoor],
    formats: ["Encastrable", "Cassette"],
    capacities: [
      "12 000 BTU/h Cassette Inverter — 220 V",
      "18 000 BTU/h Cassette Inverter — 220 V",
      "24 000 BTU/h Cassette Inverter — 220 V",
      "36 000 BTU/h Cassette Inverter — 220 V",
    ],
    specs: [
      { label: "Type", value: "Cassette 4 voies" },
      { label: "Compatibilité plafond", value: "600 × 600 mm" },
      { label: "Technologie", value: "Inverter DC" },
      { label: "Pompe de relevage", value: "Intégrée" },
      { label: "Tension", value: "220 V" },
      { label: "Contrôle", value: "Filaire premium · Wi-Fi en option" },
    ],
    highlights: [
      "Diffusion 360° homogène",
      "Pompe de relevage intégrée",
      "Inverter — silencieux nocturne",
    ],
    crossSell: [
      "megalife-cassette-r410a",
      "megalife-gainable-inverter-r32",
      "contrat-entretien-annuel",
    ],
  },
  {
    id: "megalife-cassette-r410a",
    category: "climatisation",
    brand: "MEGALIFE",
    name: "Climatiseur Cassette R410A",
    gammeLabel: "Encastrable Cassette 4 voies — On/Off R410A",
    shortDescFr:
      "Cassette plafonnière 4 voies MEGALIFE R410A en version On/Off — fiable, économique, 4 capacités de 12 000 à 36 000 BTU/h.",
    longDescFr:
      "La gamme Cassette R410A MEGALIFE en version On/Off est la solution de référence pour les commerces, restaurants, agences bancaires et résidences secondaires. Compresseur On/Off éprouvé, diffusion 4 voies, pompe de relevage intégrée, télécommande filaire fournie. Maintenance simple, robustesse éprouvée.",
    image: MEGALIFE_IMAGES.cassette,
    gallery: [MEGALIFE_IMAGES.cassette, MEGALIFE_IMAGES.cassetteAlt],
    formats: ["Encastrable", "Cassette"],
    capacities: [
      "12 000 BTU/h Cassette R410A — 220 V",
      "18 000 BTU/h Cassette R410A — 220 V",
      "24 000 BTU/h Cassette R410A — 220 V",
      "36 000 BTU/h Cassette R410A — 220 V",
    ],
    specs: [
      { label: "Type", value: "Cassette 4 voies" },
      { label: "Compatibilité plafond", value: "600 × 600 mm" },
      { label: "Technologie", value: "On/Off" },
      { label: "Réfrigérant", value: "R410A" },
      { label: "Pompe de relevage", value: "Intégrée" },
      { label: "Tension", value: "220 V" },
    ],
    highlights: [
      "Solution accessible",
      "Robuste et éprouvée",
      "Pompe de relevage intégrée",
    ],
    crossSell: [
      "megalife-cassette-inverter",
      "megalife-gainable-r410a",
      "contrat-entretien-annuel",
    ],
  },
  // ---- MEGALIFE MULTI-SPLIT — Bi-Split System (kits prêts) ----
  {
    id: "megalife-bi-split-system",
    category: "climatisation",
    brand: "MEGALIFE",
    name: "Bi-Split System MEGALIFE",
    gammeLabel: "Multi-Split — Bi-Split kits 2 unités intérieures",
    shortDescFr:
      "Kits Bi-Split MEGALIFE : 1 unité extérieure pilote 2 unités intérieures (mural Versaty / J-Smart, gainable ou cassette). Versaty jusqu'à 27 000 BTU/h, J-Smart jusqu'à 21 000 BTU/h, combinaisons gainable jusqu'à 28 000 BTU/h et cassette jusqu'à 36 000 BTU/h selon kits.",
    longDescFr:
      "La gamme Bi-Split MEGALIFE permet de climatiser 2 pièces avec une seule unité extérieure — gain d'espace, esthétique préservée, installation simplifiée. Disponible en combinaisons mural Versaty Inverter, mural J-Smart Inverter, gainable basse pression ou cassette 4 voies. Compresseur Inverter, redémarrage automatique, télécommande filaire, mise en service par technicien certifié RIZAL.",
    image: MEGALIFE_IMAGES.biSplit,
    gallery: [MEGALIFE_IMAGES.biSplitAlt, MEGALIFE_IMAGES.biSplitCreative],
    formats: ["Multi-split"],
    variants: [
      {
        id: "megalife-bi-jsmart-21k",
        title: "21 000 BTU/h Bi-Split Inverter J-Smart",
        image: "/img/products/megalife/megalife-ai-jsmart-21k-02.jpg",
        gallery: [
          "/img/products/megalife/megalife-ai-jsmart-21k-03.jpg",
          "/img/products/megalife/bi-split-jsmart-21k-kit.jpg",
        ],
      },
      {
        id: "megalife-bi-versaty-27k",
        title: "27 000 BTU/h Bi-Split Inverter Versaty",
        image: "/img/products/megalife/megalife-ai-versaty-27k-02.jpg",
        gallery: ["/img/products/megalife/bi-split-versaty-27k-lifestyle.jpg"],
      },
      {
        id: "megalife-bi-versaty-18k",
        title: "18 000 BTU/h Bi-Split Versaty Inverter",
        image: "/img/products/megalife/megalife-ai-versaty-18k-03.jpg",
        gallery: [MEGALIFE_IMAGES.biSplit],
      },
      {
        id: "megalife-bi-versaty-21k",
        title: "21 000 BTU/h Bi-Split Inverter Versaty",
        image: "/img/products/megalife/megalife-ai-versaty-21k-02.jpg",
        gallery: [MEGALIFE_IMAGES.biSplitAlt],
      },
      {
        id: "megalife-bi-jsmart-18k",
        title: "18 000 BTU/h Bi-Split Inverter J-Smart",
        image: "/img/products/megalife/megalife-ai-jsmart-18k-02.jpg",
        gallery: ["/img/products/megalife/megalife-ai-jsmart-18k-03.jpg"],
      },
      {
        id: "megalife-bi-cassette-36k",
        title: "36 000 BTU/h Bi-Split Cassette",
        image: "/img/products/megalife/megalife-ai-cassette-36k-01.jpg",
        gallery: [
          "/img/products/megalife/megalife-ai-cassette-36k-02.jpg",
          "/img/products/megalife/megalife-ai-cassette-36k-03.jpg",
        ],
      },
      {
        id: "megalife-bi-cassette-24k",
        title: "24 000 BTU/h Bi-Split Cassette",
        image: "/img/products/megalife/megalife-ai-cassette-24k-02.jpg",
        gallery: ["/img/products/megalife/megalife-ai-cassette-24k-03.jpg"],
      },
      {
        id: "megalife-bi-gainable-28k",
        title: "28 000 BTU/h Bi-Split Gainable",
        image: "/img/products/megalife/megalife-ai-gainable-28k-01.jpg",
        gallery: ["/img/products/megalife/megalife-ai-gainable-28k-03.jpg"],
      },
      {
        id: "megalife-bi-gainable-24k",
        title: "24 000 BTU/h Bi-Split Gainable",
        image: "/img/products/megalife/megalife-ai-gainable-24k-01.jpg",
        gallery: ["/img/products/megalife/megalife-ai-gainable-24k-03.jpg"],
      },
      {
        id: "megalife-bi-gainable-18k",
        title: "18 000 BTU/h Bi-Split Gainable",
        image: "/img/products/megalife/megalife-ai-gainable-18k-03.jpg",
        gallery: [MEGALIFE_IMAGES.gainableIndoor],
      },
    ],
    specs: [
      { label: "Configuration", value: "1 ext. → 2 int." },
      { label: "Technologie", value: "Inverter DC" },
      { label: "Réfrigérant", value: "R32 / R410A selon modèle" },
      { label: "Combinaisons int.", value: "Mural Versaty, Mural J-Smart, Gainable, Cassette" },
      { label: "Tubing max.", value: "Jusqu'à 25 m total" },
      { label: "Mise en service", value: "Technicien RIZAL certifié" },
    ],
    highlights: [
      "1 ext. = 2 pièces climatisées",
      "Mix possible : mural + gainable / mural + cassette",
      "10 modèles catalogue (libellés vitrine MEGALIFE)",
    ],
    crossSell: ["support-mural-inox", "contrat-entretien-annuel"],
  },
  {
    id: "megalife-mobile",
    category: "climatisation",
    brand: "MEGALIFE",
    name: "Climatiseur Mobile MEGALIFE",
    gammeLabel: "Mobile Monobloc — 7 000 à 16 000 BTU/h",
    shortDescFr: "Climatiseurs mobiles MEGALIFE, écran LED, roulettes, gaz écologique R290 — sans installation.",
    longDescFr:
      "Solution sans travaux : 5 capacités (7 000, 9 000, 12 000, 14 000 et 16 000 BTU/h), écran LED, télécommande, kit fenêtre fourni, déshumidificateur intégré. Réfrigérant R290 à très faible impact environnemental.",
    image: MEGALIFE_IMAGES.mobile,
    gallery: [MEGALIFE_IMAGES.mobileHero, INGELEC_IMAGES.mobileLifestyle],
    formats: ["Mobile"],
    capacities: ["7 000 BTU/h", "9 000 BTU/h", "12 000 BTU/h", "14 000 BTU/h", "16 000 BTU/h"],
    variants: [
      {
        id: "megalife-mobile-7k",
        title: "7 000 BTU/h — Climatiseur Mobile MEGALIFE",
        image: INGELEC_IMAGES.mobile,
        gallery: [INGELEC_IMAGES.mobileLifestyle],
      },
      {
        id: "megalife-mobile-9k",
        title: "9 000 BTU/h — Climatiseur Mobile MEGALIFE",
        image: INGELEC_IMAGES.mobileLifestyle,
        gallery: [INGELEC_IMAGES.mobileDetail],
      },
      {
        id: "megalife-mobile-12k",
        title: "12 000 BTU/h — Climatiseur Mobile MEGALIFE",
        image: INGELEC_IMAGES.mobile,
        gallery: [INGELEC_IMAGES.mobileLifestyle],
      },
      {
        id: "megalife-mobile-14k",
        title: "14 000 BTU/h — Climatiseur Mobile MEGALIFE",
        image: INGELEC_IMAGES.mobileLifestyle,
        gallery: [INGELEC_IMAGES.mobileDetail],
      },
      {
        id: "megalife-mobile-16k",
        title: "16 000 BTU/h — Climatiseur Mobile MEGALIFE",
        image: INGELEC_IMAGES.mobile,
        gallery: [INGELEC_IMAGES.mobileLifestyle],
      },
    ],
    specs: [
      { label: "Type", value: "Monobloc mobile" },
      { label: "Réfrigérant", value: "R290 (écologique)" },
      { label: "Écran", value: "LED" },
      { label: "Kit fenêtre", value: "Fourni" },
      { label: "Déshumidificateur", value: "Intégré" },
    ],
    highlights: ["Sans installation", "5 puissances", "Réfrigérant R290 vert"],
    crossSell: ["megalife-bi-split-system", "contrat-entretien-annuel"],
  },
  // ========== INGELEC ==========
  {
    id: "ingelec-mural-inverter",
    category: "climatisation",
    brand: "INGELEC",
    name: "INGELEC Mural Split Inverter",
    gammeLabel: "Mural Split — Référence marocaine",
    shortDescFr: "La gamme mural Inverter INGELEC, fabriquée pour le climat marocain, robuste et économe.",
    longDescFr:
      "INGELEC, fabricant marocain de référence, propose une gamme mural split Inverter conçue spécifiquement pour les conditions extrêmes du Maroc (jusqu'à 52°C extérieur). Compresseur garantie longue durée, R32, fonctions Turbo et Sleep.",
    image: INGELEC_IMAGES.muralInverter,
    gallery: [INGELEC_IMAGES.muralInverterGallery, INGELEC_IMAGES.muralInverter],
    formats: ["Mural"],
    capacities: ["9 000 BTU/h", "12 000 BTU/h", "18 000 BTU/h", "24 000 BTU/h", "36 000 BTU/h", "48 000 BTU/h"],
    specs: [
      { label: "Technologie", value: "Inverter" },
      { label: "Réfrigérant", value: "R32" },
      { label: "Adapté à", value: "Climat marocain (jusqu'à 52°C)" },
      { label: "Garantie", value: "Constructeur INGELEC" },
    ],
    highlights: ["Marque marocaine", "Adapté climat extrême", "Réseau SAV national"],
    crossSell: ["support-mural-inox", "contrat-entretien-annuel"],
    badge: "Made in Morocco",
  },
  {
    id: "ingelec-mural-onoff",
    category: "climatisation",
    brand: "INGELEC",
    name: "INGELEC Mural Split On/Off",
    gammeLabel: "Mural Split — Solution accessible",
    shortDescFr: "Gamme On/Off INGELEC, simple, fiable, idéale pour résidences secondaires et locations.",
    image: INGELEC_IMAGES.muralOnOff,
    gallery: [INGELEC_IMAGES.muralOnOffSystem, INGELEC_IMAGES.muralOnOff],
    formats: ["Mural"],
    capacities: ["9 000 BTU/h", "12 000 BTU/h", "18 000 BTU/h", "24 000 BTU/h"],
    specs: [
      { label: "Technologie", value: "On/Off" },
      { label: "Robustesse", value: "Élevée" },
      { label: "Garantie", value: "Constructeur INGELEC" },
    ],
    highlights: ["Robuste", "Maintenance simple", "Solution éprouvée"],
    crossSell: ["support-mural-inox", "contrat-entretien-annuel"],
  },
  {
    id: "ingelec-cassette-inverter",
    category: "climatisation",
    brand: "INGELEC",
    name: "INGELEC Cassette Inverter",
    gammeLabel: "Encastrable — IGCLCI18I à IGCLCI60I",
    shortDescFr: "Cassette plafond Inverter INGELEC, références IGCLCI18I à IGCLCI60I, 18 000 à 55 000 BTU/h.",
    longDescFr:
      "Système split avec unité intérieure encastrée dans le plafond. Diffusion homogène 4 voies, pompe de relevage intégrée, télécommande infrarouge, redémarrage automatique, dégivrage intelligent, autodiagnostic. EER jusqu'à 3,18 / COP jusqu'à 3,72. Contrôle filaire, centralisé ou Wi-Fi en option.",
    image: INGELEC_IMAGES.cassette,
    gallery: [INGELEC_IMAGES.cassetteKit, INGELEC_IMAGES.cassette],
    formats: ["Encastrable", "Cassette"],
    capacities: [
      "18 000 BTU/h",
      "24 000 BTU/h",
      "36 000 BTU/h",
      "48 000 BTU/h",
      "55 000 BTU/h",
    ],
    specs: [
      { label: "Références", value: "IGCLCI18I / 24I / 36I / 48I / 60I" },
      { label: "EER / COP max", value: "3,18 / 3,72 (W/W)" },
      { label: "Pompe de relevage", value: "Intégrée" },
      { label: "Contrôle", value: "Filaire / Centralisé / Wi-Fi (option)" },
      { label: "Filtre", value: "Longue durée" },
    ],
    highlights: ["EER jusqu'à 3,18", "Pompe de relevage", "5 capacités"],
    crossSell: ["ingelec-gainable-inverter", "contrat-entretien-annuel"],
  },
  {
    id: "ingelec-gainable-inverter",
    category: "climatisation",
    brand: "INGELEC",
    name: "INGELEC Gainable Inverter",
    gammeLabel: "Encastrable — IGCLGI12I à IGCLGI60I",
    shortDescFr: "Gainable Inverter INGELEC — installation faux-plafond, diffusion par gaines, 12 000 à 55 000 BTU/h.",
    longDescFr:
      "Climatiseur gainable Inverter INGELEC pour intégration totale dans le faux-plafond. Performance optimale, fonctionnement silencieux, ailettes aluminium hydrophile, refroidissement à basse température ambiante, flux d'air 3D. Contrôle filaire fourni en série, centralisé/Wi-Fi en option.",
    image: INGELEC_IMAGES.gainable,
    gallery: [INGELEC_IMAGES.gainableKit, INGELEC_IMAGES.gainable],
    formats: ["Encastrable", "Gainable"],
    capacities: [
      "12 000 BTU/h",
      "18 000 BTU/h",
      "24 000 BTU/h",
      "36 000 BTU/h",
      "48 000 BTU/h",
      "55 000 BTU/h",
    ],
    specs: [
      { label: "Références", value: "IGCLGI12I / 18I / 24I / 36I / 48I / 60I" },
      { label: "EER / COP max", value: "3,20 / 3,66 (W/W)" },
      { label: "Ailettes", value: "Aluminium hydrophile" },
      { label: "Flux d'air", value: "3D" },
      { label: "Contrôle filaire", value: "Fourni en série" },
    ],
    highlights: ["6 capacités", "Flux d'air 3D", "Refroidissement basse température"],
    crossSell: ["ingelec-cassette-inverter", "contrat-entretien-annuel"],
  },
  // ---- INGELEC MULTI-SPLIT ----
  {
    id: "ingelec-multi-split",
    category: "climatisation",
    brand: "INGELEC",
    name: "INGELEC Multi-Split Inverter",
    gammeLabel: "Multi-Split — Bi / Tri / Quadri-split",
    shortDescFr:
      "Multi-split INGELEC Inverter conçu pour le climat marocain : 1 unité extérieure pilote 2 à 4 unités intérieures (mural, cassette ou gainable).",
    longDescFr:
      "La gamme Multi-Split INGELEC permet d'équiper plusieurs pièces avec une seule unité extérieure, idéale pour villas, riads et appartements duplex. Compresseur Inverter, gaz R32, ailettes anti-corrosion adaptées au climat marocain (jusqu'à 52°C extérieur). Possibilité de mixer murals, cassettes et gainables. Garantie constructeur INGELEC, réseau SAV national.",
    image: INGELEC_IMAGES.multiSplit,
    gallery: [],
    formats: ["Multi-split"],
    capacities: [
      "Bi-Split — 2 unités intérieures",
      "Tri-Split — 3 unités intérieures",
      "Quadri-Split — 4 unités intérieures",
    ],
    specs: [
      { label: "Configuration", value: "Bi / Tri / Quadri-split" },
      { label: "Technologie", value: "Inverter DC" },
      { label: "Réfrigérant", value: "R32" },
      { label: "Compatibilité int.", value: "Mural, Cassette, Gainable" },
      { label: "Ailettes", value: "Anti-corrosion" },
      { label: "Garantie", value: "Constructeur INGELEC" },
    ],
    highlights: [
      "1 ext. → jusqu'à 4 pièces",
      "Adapté climat marocain (52°C)",
      "Mix mural/cassette/gainable possible",
    ],
    crossSell: [
      "ingelec-cassette-inverter",
      "ingelec-gainable-inverter",
      "ingelec-mural-inverter",
      "contrat-entretien-annuel",
    ],
    badge: "Multi-Split",
  },
  // ---- INGELEC MOBILE ----
  {
    id: "ingelec-mobile",
    category: "climatisation",
    brand: "INGELEC",
    name: "INGELEC Climatiseur Mobile",
    gammeLabel: "Mobile Monobloc — Sans installation",
    shortDescFr:
      "Climatiseur mobile INGELEC sur roulettes — solution sans travaux pour résidences secondaires, locations et usage saisonnier.",
    longDescFr:
      "La gamme mobile INGELEC offre une solution Plug & Play sans installation : roulettes pivotantes, kit fenêtre fourni, télécommande, écran LED, déshumidificateur intégré. Idéale pour résidences secondaires, riads en location, bureaux temporaires. Marque marocaine, SAV national.",
    image: INGELEC_IMAGES.mobile,
    gallery: [INGELEC_IMAGES.mobileLifestyle, INGELEC_IMAGES.mobileDetail],
    formats: ["Mobile"],
    capacities: ["9 000 BTU/h", "12 000 BTU/h"],
    specs: [
      { label: "Type", value: "Monobloc mobile" },
      { label: "Roulettes", value: "Polyvalentes" },
      { label: "Kit fenêtre", value: "Fourni" },
      { label: "Déshumidificateur", value: "Intégré" },
      { label: "Garantie", value: "Constructeur INGELEC" },
    ],
    highlights: ["Sans installation", "SAV national", "Plug & Play"],
    crossSell: ["ingelec-mural-inverter", "contrat-entretien-annuel"],
  },
  // ========== LG ==========
  {
    id: "lg-artcool-mirror",
    category: "climatisation",
    brand: "LG",
    name: "LG ARTCOOL Mirror UVnano",
    gammeLabel: "Mural Split Design — DUAL Inverter, Wi-Fi, Chauffage",
    shortDescFr: "Façade miroir, technologie UVnano, DUAL Inverter Compressor, Wi-Fi, Plasmaster Ionizer+.",
    longDescFr:
      "L'icône design de LG : façade miroir élégante, technologie UVnano qui réduit jusqu'à 99 % des bactéries sur le ventilateur, DUAL Inverter Compressor pour 70 % d'économie d'énergie, Plasmaster Ionizer+ pour la qualité de l'air, contrôle Wi-Fi via l'app LG ThinQ.",
    image: LG_IMAGES.artcoolMirror,
    gallery: [LG_IMAGES.artcoolMirror2, LG_IMAGES.artcoolMirror3],
    formats: ["Mural"],
    capacities: ["9 000 BTU/h", "12 000 BTU/h", "18 000 BTU/h", "24 000 BTU/h"],
    specs: [
      { label: "Compresseur", value: "DUAL Inverter — garantie 10 ans" },
      { label: "Design", value: "Façade Miroir" },
      { label: "UVnano", value: "Réduit 99 % des bactéries" },
      { label: "Plasmaster", value: "Ionizer+" },
      { label: "Wi-Fi", value: "LG ThinQ" },
      { label: "Réfrigérant", value: "R32" },
    ],
    highlights: ["Façade Miroir", "UVnano hygiène", "Garantie compresseur 10 ans"],
    crossSell: ["lg-dualcool-premium", "support-mural-inox", "contrat-entretien-annuel"],
    badge: "Premium",
  },
  {
    id: "lg-artcool-gallery",
    category: "climatisation",
    brand: "LG",
    name: "LG ARTCOOL Gallery",
    gammeLabel: "Mural Split Design — Cadre photo personnalisable",
    shortDescFr: "Le climatiseur qui devient une œuvre d'art : façade cadre photo personnalisable.",
    longDescFr:
      "Insérez votre œuvre d'art ou photo personnalisée dans le cadre frontal. DUAL Inverter Compressor, Plasmaster Ionizer+, R32, contrôle Wi-Fi LG ThinQ. Pour ceux qui refusent le compromis entre confort et esthétique.",
    image: LG_IMAGES.artcoolGallery,
    gallery: [LG_IMAGES.artcoolGallery2, LG_IMAGES.artcoolGallery3],
    formats: ["Mural"],
    capacities: ["9 000 BTU/h", "12 000 BTU/h"],
    specs: [
      { label: "Compresseur", value: "DUAL Inverter" },
      { label: "Design", value: "Cadre photo personnalisable" },
      { label: "Wi-Fi", value: "LG ThinQ" },
      { label: "Plasmaster", value: "Ionizer+" },
    ],
    highlights: ["Cadre photo personnalisable", "Œuvre d'art murale", "DUAL Inverter"],
    crossSell: ["lg-artcool-mirror", "lg-dualcool-premium"],
    badge: "Édition Galerie",
  },
  {
    id: "lg-dualcool-premium",
    category: "climatisation",
    brand: "LG",
    name: "LG DUALCOOL Premium",
    gammeLabel: "Mural Split — DUAL Inverter haute performance",
    shortDescFr: "Refroidissement rapide en 30 secondes, fonctionnel jusqu'à 54°C extérieur — idéal climat marocain.",
    longDescFr:
      "Le DUALCOOL Premium combine puissance et efficacité : DUAL Inverter Compressor (garantie 10 ans), refroidissement ultra-rapide en 30 secondes, fonctionne jusqu'à 54°C extérieur — la référence pour les villas du Sud marocain. Wi-Fi, mode silencieux 19 dB.",
    image: LG_IMAGES.dualcool,
    gallery: [LG_IMAGES.dualcool2, LG_IMAGES.dualcool3],
    formats: ["Mural"],
    capacities: ["9 000 BTU/h", "12 000 BTU/h", "18 000 BTU/h", "24 000 BTU/h"],
    specs: [
      { label: "Compresseur", value: "DUAL Inverter — garantie 10 ans" },
      { label: "Plage", value: "Fonctionne jusqu'à 54°C ext." },
      { label: "Niveau sonore", value: "19 dB(A) en mode nuit" },
      { label: "Wi-Fi", value: "LG ThinQ" },
      { label: "Réfrigérant", value: "R32" },
    ],
    highlights: ["Fonctionne à 54°C", "19 dB silencieux", "Refroidissement 30s"],
    crossSell: ["lg-artcool-mirror", "support-mural-inox"],
  },
  {
    id: "lg-multi-split",
    category: "climatisation",
    brand: "LG",
    name: "LG Multi-Split",
    gammeLabel: "Multi-split — 1 unité extérieure, jusqu'à 5 intérieures",
    shortDescFr: "Une seule unité extérieure pilote jusqu'à 5 unités intérieures (mural, cassette, gainable mixés).",
    longDescFr:
      "La solution LG Multi-Split réduit l'encombrement extérieur tout en climatisant toute la villa. Inverter avancé, capteur de pression pour atteindre la consigne 30 % plus rapidement, mode nuit silencieux. Compatible avec tous les designs intérieurs LG (ARTCOOL, Standard, Cassette, Gainable).",
    image: LG_IMAGES.multiSplit,
    gallery: [LG_IMAGES.multiSplitInterior, LG_IMAGES.multiSplitKitchen],
    formats: ["Multi-split"],
    capacities: ["2 → 5 unités intérieures"],
    specs: [
      { label: "Capacité système", value: "Jusqu'à 9 unités intérieures (modèles XL)" },
      { label: "Technologie", value: "Inverter + capteur de pression" },
      { label: "Intérieures compatibles", value: "Mural, Cassette, Gainable, Console" },
      { label: "Wi-Fi", value: "LG ThinQ par unité" },
    ],
    highlights: ["1 ext. = jusqu'à 5 int.", "Capteur de pression", "Mix de designs"],
    crossSell: ["lg-multi-v-5", "lg-artcool-mirror"],
  },
  {
    id: "lg-multi-v-5",
    category: "climatisation",
    brand: "LG",
    name: "LG MULTI V 5 (DRV / VRF)",
    gammeLabel: "VRF — Solution villas de prestige & complexes",
    shortDescFr: "Système VRF haut rendement LG pour grandes villas, hôtels boutique et résidences premium.",
    longDescFr:
      "Le MULTI V 5 est la solution VRF la plus avancée de LG : haute efficacité énergétique, performance même par températures extrêmes, flexibilité totale (mural, cassette, gainable, console mixés), contrôle centralisé GMV, intégration domotique. La référence pour les projets villas haut de gamme et résidences de plusieurs centaines de m².",
    image: LG_IMAGES.multiV5,
    gallery: [LG_IMAGES.multiV52, LG_IMAGES.multiV53],
    formats: ["VRF", "Encastrable", "Multi-split"],
    capacities: ["8 → 96 HP (selon configuration)"],
    specs: [
      { label: "Type", value: "VRF (DRV) à débit de réfrigérant variable" },
      { label: "Application", value: "Villas, hôtels, résidences" },
      { label: "Efficacité", value: "Premium — leader marché" },
      { label: "Contrôle", value: "Centralisé + BMS + Wi-Fi" },
    ],
    highlights: ["VRF premium", "Pour villas de prestige", "Pilotage centralisé"],
    crossSell: ["lg-multi-split", "onduleur-solax-x3-neo"],
    badge: "Villa de Prestige",
  },
  {
    id: "lg-cassette-gainable",
    category: "climatisation",
    brand: "LG",
    name: "LG Cassette & Gainable",
    gammeLabel: "Encastrable — Compatible Multi-Split & VRF",
    shortDescFr: "Unités intérieures cassette 4 voies et gainable LG, compatibles Multi-Split et VRF MULTI V.",
    image: LG_IMAGES.cassetteGainable,
    gallery: [LG_IMAGES.cassetteGainable2, LG_IMAGES.cassetteGainable3],
    formats: ["Encastrable", "Cassette", "Gainable"],
    capacities: ["12 000 → 60 000 BTU/h"],
    specs: [
      { label: "Type", value: "Cassette 4 voies / Gainable mid-pressure" },
      { label: "Compatibilité", value: "Multi-Split & VRF MULTI V" },
      { label: "Télécommande filaire", value: "Premium incluse" },
    ],
    highlights: ["Encastrement parfait", "Compatible VRF"],
    crossSell: ["lg-multi-v-5", "lg-multi-split"],
  },
  {
    id: "lg-mobile",
    category: "climatisation",
    brand: "LG",
    name: "LG Climatiseur Mobile",
    gammeLabel: "Mobile — Sans installation",
    shortDescFr: "Climatiseurs portables LG, déplaçables sur roulettes, pour usage saisonnier et événementiel.",
    image: LG_IMAGES.mobile,
    gallery: [LG_IMAGES.mobile2, LG_IMAGES.mobile3],
    formats: ["Mobile"],
    capacities: ["9 000 BTU/h", "12 000 BTU/h"],
    specs: [
      { label: "Type", value: "Monobloc mobile" },
      { label: "Roulettes", value: "Polyvalentes" },
      { label: "Kit fenêtre", value: "Fourni" },
    ],
    highlights: ["Sans installation", "Plug & Play"],
    crossSell: ["lg-dualcool-premium"],
  },
  // ========== TRANE ==========
  {
    id: "trane-split-standard",
    category: "climatisation",
    brand: "TRANE",
    name: "TRANE Split mural Standard",
    gammeLabel: "Inverter & R410 — 9 000 à 24 000 BTU/h",
    shortDescFr:
      "Splits muraux TRANE pour le Maroc : versions Inverter et R410 (R410A) — ligne couramment proposée par les distributeurs TRANE.",
    longDescFr:
      "Les splits muraux standard TRANE couvrent les usages résidentiels et petits commerces : modulation Inverter pour le confort, ou série R410 On/Off pour un excellent rapport prix / performance. Les puissances les plus répandues au Maroc vont du 9 000 au 24 000 BTU/h (voir fiches distributeurs comme Atlas Electro « Trane Maroc »). Garantie constructeur 3 ans, mise en œuvre par techniciens RIZAL. Les références précises peuvent varier selon stock importateur.",
    image: TRANE_SPLIT_STANDARD_IMAGES.packshot,
    gallery: [
      TRANE_SPLIT_STANDARD_IMAGES.moroccoCasablanca,
      TRANE_SPLIT_STANDARD_IMAGES.moroccoRiad,
    ],
    formats: ["Mural"],
    capacities: [
      "9 000 BTU/h Inverter",
      "12 000 BTU/h Inverter",
      "18 000 BTU/h Inverter",
      "24 000 BTU/h R410A",
      "9 000 / 12 000 / 18 000 BTU/h R410 (On/Off)",
    ],
    specs: [
      { label: "Réfrigérant", value: "R410A" },
      { label: "Garantie", value: "3 ans constructeur" },
      { label: "Usage", value: "Résidentiel & petit tertiaire" },
    ],
    highlights: ["Inverter ou R410", "9 → 24 k BTU/h", "Garantie 3 ans"],
    crossSell: ["trane-split-black-mirror", "trane-multisplit"],
  },
  {
    id: "trane-split-black-mirror",
    category: "climatisation",
    brand: "TRANE",
    name: "TRANE Black Mirror",
    gammeLabel: "Design miroir — R410 — 9 000 à 24 000 BTU/h",
    shortDescFr:
      "Façade miroir élégante, technologie TRANE jusqu'à ~40 % d'économies d'énergie selon usages — série visible chez distributeurs TRANE Maroc.",
    longDescFr:
      "La ligne Black Mirror associe esthétique contemporaine façade réfléchissante et compresseur Inverter TRANE pour un confort ciblé et une qualité d'air soignée. Capacités usuellement proposées : 9 000, 12 000, 18 000 et 24 000 BTU/h R410A (sources distributeurs Atlas Electro « Trane Maroc »). Parfait pour salons et suites où le design mural compte autant que la performance. Installation et entretien RIZAL, garantie 3 ans constructeur sous réserve des conditions constructeur.",
    image: TRANE_BLACK_MIRROR_IMAGES.hero,
    gallery: [
      TRANE_BLACK_MIRROR_IMAGES.detail,
      TRANE_SPLIT_STANDARD_IMAGES.moroccoRiad,
    ],
    formats: ["Mural"],
    capacities: [
      "9 000 BTU/h R410A",
      "12 000 BTU/h R410A",
      "18 000 BTU/h R410A",
      "24 000 BTU/h R410A",
    ],
    specs: [
      { label: "Design", value: "Façade Black Mirror" },
      { label: "Réfrigérant", value: "R410A" },
      { label: "Garantie", value: "3 ans constructeur" },
    ],
    highlights: ["Design miroir", "Inverter", "Jusqu'à grandes surfaces selon puissance"],
    crossSell: ["trane-split-standard", "trane-gainable"],
    badge: "Design",
  },
  {
    id: "trane-cassette-onoff",
    category: "climatisation",
    brand: "TRANE",
    name: "TRANE Cassette",
    gammeLabel: "Encastrable Plafond — 12 000 à 60 000 BTU/h",
    shortDescFr: "Cassette TRANE pour bureaux, villas et commerces — fiabilité américaine, garantie 3 ans.",
    longDescFr:
      "TRANE, marque américaine référente du CVC mondial. La gamme cassette TRANE assure une diffusion homogène pour grands espaces : salles de réunion, salons de villa, commerces. Disponible en 12 000, 18 000, 24 000, 36 000, 48 000 et 60 000 BTU/h. Garantie constructeur 3 ans.",
    image: TRANE_CASSETTE_IMAGES.hero,
    gallery: [TRANE_CASSETTE_IMAGES.office],
    formats: ["Encastrable", "Cassette"],
    capacities: [
      "12 000 BTU/h (3,5 kW)",
      "18 000 BTU/h (5,3 kW)",
      "24 000 BTU/h (7 kW)",
      "36 000 BTU/h",
      "48 000 BTU/h (14 kW)",
      "60 000 BTU/h (16 kW)",
    ],
    specs: [
      { label: "Marque", value: "TRANE — Trane Technologies (USA)" },
      { label: "Garantie", value: "3 ans constructeur" },
      { label: "Application", value: "Bureaux, villas, commerces" },
      { label: "Adapté", value: "Climat marocain (haute température)" },
    ],
    highlights: ["Marque américaine", "Garantie 3 ans", "6 capacités"],
    crossSell: ["trane-multisplit", "trane-vrf"],
    badge: "Premium USA",
  },
  {
    id: "trane-multisplit",
    category: "climatisation",
    brand: "TRANE",
    name: "TRANE Multi-Split Inverter",
    gammeLabel: "Multi-split — Confort silencieux haut de gamme",
    shortDescFr: "Multi-split TRANE pour habitations complexes et villas — silence, intégration domotique.",
    longDescFr:
      "Les systèmes Multi-Split TRANE permettent de climatiser plusieurs pièces avec une seule unité extérieure, parfaits pour les villas et bâtiments commerciaux. Performance optimisée pour les hautes températures du Maroc, niveau sonore réduit, intégration domotique disponible.",
    image: TRANE_MULTISPLIT_IMAGES.hero,
    gallery: [
      TRANE_SPLIT_STANDARD_IMAGES.moroccoCasablanca,
      TRANE_SPLIT_STANDARD_IMAGES.moroccoRiad,
    ],
    formats: ["Multi-split"],
    capacities: ["Bi-split", "Tri-split", "Quadri-split"],
    specs: [
      { label: "Technologie", value: "Inverter" },
      { label: "Garantie", value: "3 ans constructeur" },
      { label: "Intégration", value: "Domotique compatible" },
    ],
    highlights: ["Silence premium", "Domotique", "Inverter haut rendement"],
    crossSell: ["trane-cassette-onoff", "trane-vrf"],
  },
  {
    id: "trane-gainable",
    category: "climatisation",
    brand: "TRANE",
    name: "TRANE Gainable",
    gammeLabel: "Encastrable Faux-Plafond — Light Commercial",
    shortDescFr:
      "Gainable TRANE — Inverter 12–18 kBTU/h et On/Off 18 kBTU/h au catalogue distributeur ; diffusion invisible pour villas et petit tertiaire.",
    longDescFr:
      "Les unités gainables TRANE se logent dans les plenums faux plafond pour une diffusion discrète dans villas, cliniques et petit tertiaire. Les références fréquentes au Maroc incluent les variantes Inverter 12 et 18 kBTU ainsi qu'une série 18 kBTU On/Off selon catalogue importateur ; pression statique adaptée conduit gainé. Pose, équilibrage et entretien par techniciens RIZAL sous garantie constructeur 3 ans.",
    image: TRANE_GAINABLE_IMAGES.hero,
    gallery: [TRANE_GAINABLE_IMAGES.grille],
    formats: ["Encastrable", "Gainable"],
    capacities: [
      "12 000 BTU/h Inverter (3,5 kW)",
      "18 000 BTU/h Inverter",
      "18 000 BTU/h On/Off",
    ],
    specs: [
      { label: "Application", value: "Villas, hôtels, cliniques" },
      { label: "Pression statique", value: "Mid-Pressure (MSP)" },
      { label: "Garantie", value: "3 ans constructeur" },
    ],
    highlights: ["Light Commercial", "Pour villas haut de gamme"],
    crossSell: ["trane-cassette-onoff", "trane-vrf"],
  },
  {
    id: "trane-vrf",
    category: "climatisation",
    brand: "TRANE",
    name: "TRANE VRF (VRV / DRV / DVM)",
    gammeLabel: "VRF — Trane Advantage VRF Systems",
    shortDescFr: "Solution VRF TRANE — débit de réfrigérant variable, pour grands programmes & complexes résidentiels.",
    longDescFr:
      "Trane Advantage VRF Systems (R410A) — modèles 4TVC0009-0048 pour cassettes 4 voies, configurations gainable basse et haute pression, slim duct. Pilotage VRF Wired/Wireless Remote, Enterprise Management Software, Auto-Commissioning Tool. Pour grandes villas, hôtels et tours résidentielles.",
    image: TRANE_VRF_IMAGES.hero,
    gallery: [
      TRANE_MULTISPLIT_IMAGES.hero,
      TRANE_CASSETTE_IMAGES.office,
      TRANE_GAINABLE_IMAGES.grille,
    ],
    formats: ["VRF", "Encastrable"],
    capacities: ["9 000 → 48 000 BTU/h par unité intérieure"],
    specs: [
      { label: "Système", value: "Trane Advantage VRF" },
      { label: "Réfrigérant", value: "R410A" },
      { label: "Modèles", value: "4TVC0009 / 0018 / 0024 / 0030 / 0036 / 0048" },
      { label: "Contrôle", value: "VRF Wired / Wireless / Enterprise Software" },
    ],
    highlights: ["Trane Advantage VRF", "Enterprise Software", "Grands projets"],
    crossSell: ["trane-cassette-onoff", "trane-gainable", "onduleur-solax-x3-neo"],
    badge: "VRF Pro",
  },
  {
    id: "trane-rental",
    category: "climatisation",
    brand: "TRANE",
    name: "TRANE Rental — Location Chillers",
    gammeLabel: "Location de groupes frigorifiques",
    shortDescFr: "Solutions de location de chillers TRANE — événementiel, chantier, urgence climatique villa.",
    longDescFr:
      "Trane Rental MEA est le leader marocain de la location CVC : groupes frigorifiques court et long terme, conteneurs réfrigérés, chauffage temporaire. Idéal hôtels en rénovation, événements, défaillance climatisation villa, pics de demande estivaux. Couverture Essaouira et national.",
    image: TRANE_RENTAL_IMAGES.hero,
    gallery: [TRANE_VRF_IMAGES.hero],
    formats: ["Mobile"],
    capacities: ["Sur étude — toutes capacités"],
    specs: [
      { label: "Service", value: "Location courte / longue durée" },
      { label: "Couverture", value: "Essaouira et national" },
      { label: "Support", value: "24h/24, 7j/7" },
    ],
    highlights: ["Location flexible", "Disponibilité rapide", "Support 24/7"],
    crossSell: ["trane-vrf", "trane-cassette-onoff"],
    badge: "Service",
  },
  // ---- TRANE MOBILE ----
  {
    id: "trane-mobile",
    category: "climatisation",
    brand: "TRANE",
    name: "TRANE Climatiseur Mobile",
    gammeLabel: "Mobile Premium — Light Commercial",
    shortDescFr:
      "Climatiseur mobile TRANE — solution premium sans installation, qualité commerciale américaine pour usage résidentiel haut de gamme.",
    longDescFr:
      "Le mobile TRANE allie la robustesse industrielle de la marque américaine au confort domestique : compresseur haute efficacité, structure renforcée, kit fenêtre premium, télécommande filaire en option, déshumidificateur intégré. Idéal pour villas en cours de rénovation, bureaux d'architectes, espaces événementiels. Garantie 3 ans constructeur.",
    image: TRANE_MOBILE_IMAGES.hero,
    gallery: [TRANE_MOBILE_IMAGES.lifestyle, TRANE_MOBILE_IMAGES.studio],
    formats: ["Mobile"],
    capacities: ["12 000 BTU/h", "14 000 BTU/h"],
    specs: [
      { label: "Type", value: "Monobloc mobile premium" },
      { label: "Marque", value: "TRANE — Trane Technologies (USA)" },
      { label: "Garantie", value: "3 ans constructeur" },
      { label: "Kit fenêtre", value: "Premium fourni" },
      { label: "Déshumidificateur", value: "Intégré" },
    ],
    highlights: ["Qualité commerciale USA", "Garantie 3 ans", "Structure renforcée"],
    crossSell: ["trane-cassette-onoff", "trane-rental"],
    badge: "Premium USA",
  },
];
