import type { CatalogItem } from "@/types/catalog";

/** Visuels locaux — évite les liens externes bloqués dans le navigateur. */
const SERVICES_IMAGES = {
  poolSkimmer: "/img/products/piscine/construction/piscine-skimmer-classique.jpg",
  poolDebordement: "/img/products/piscine/construction/piscine-debordement.jpg",
  poolCouloir: "/img/products/piscine/construction/piscine-couloir-nage.jpg",
  poolLagon: "/img/products/piscine/construction/piscine-lagon-naturelle.jpg",
  poolSpa: "/img/products/piscine/construction/piscine-spa-jacuzzi.jpg",
  renovation: "/img/products/renovation/renovation-villa-complete.jpg",
  cuisine: "/img/products/renovation/renovation-cuisine-equipee.jpg",
  marbre: "/img/products/renovation/renovation-marbre-tadelakt.jpg",
  domotique: "/img/products/renovation/domotique-villa-knx.jpg",
  adoucisseur: "/img/products/traitement-eau/adoucisseur-villa.jpg",
  osmoseur: "/img/products/traitement-eau/osmoseur-6-etages.jpg",
  osmoseVilla: "/img/products/traitement-eau/osmose-inverse-villa.jpg",
  lampeUv: "/img/products/traitement-eau/lampe-uv-sterilisation.jpg",
} as const;

export const servicesItems: CatalogItem[] = [
  // ========== PISCINE ==========
  {
    id: "piscine-skimmer-classique",
    category: "piscine",
    name: "Piscine Skimmer Classique",
    gammeLabel: "Construction sur-mesure — 8×4, 10×5, 12×6 m",
    shortDescFr: "Piscine skimmer en béton armé, étanchéité liner armé 150/100, livraison 8 - 12 semaines.",
    longDescFr:
      "Construction de piscine skimmer clé-en-main : étude de sol, terrassement, structure béton armé monobloc, étanchéité liner armé 150/100 ou polyester, revêtement carrelage / pierre / mosaïque, filtration sable ou diatomée, traitement au chlore ou électrolyse au sel. Délais respectés, garantie décennale.",
    image: SERVICES_IMAGES.poolSkimmer,
    specs: [
      { label: "Dimensions standard", value: "8×4, 10×5, 12×6 m" },
      { label: "Structure", value: "Béton armé monobloc" },
      { label: "Étanchéité", value: "Liner armé 150/100 ou polyester" },
      { label: "Délais", value: "8 - 12 semaines" },
      { label: "Garantie", value: "Décennale" },
    ],
    highlights: ["Délais respectés", "Garantie décennale", "Sur-mesure"],
    crossSell: ["electrolyseur-sel", "pac-piscine", "eclairage-led-rgb"],
  },
  {
    id: "piscine-debordement",
    category: "piscine",
    name: "Piscine à Débordement",
    gammeLabel: "Effet miroir — Cascade — Vue panoramique",
    shortDescFr: "Piscine à débordement (effet miroir ou cascade) pour villas avec vue. Le summum du luxe extérieur.",
    longDescFr:
      "Piscine à débordement sur mesure : effet miroir 360°, débordement cascade ou couloir périphérique. Bassin tampon, double système de pompage, niveau régulé électroniquement. Revêtement pierre naturelle ou mosaïque vénitienne. Délais 12 - 16 semaines, garantie décennale.",
    image: SERVICES_IMAGES.poolDebordement,
    specs: [
      { label: "Type", value: "Débordement miroir / cascade" },
      { label: "Système", value: "Bassin tampon + régulation électronique" },
      { label: "Revêtement", value: "Pierre naturelle ou mosaïque" },
      { label: "Délais", value: "12 - 16 semaines" },
    ],
    highlights: ["Effet miroir", "Vue panoramique", "Pierre naturelle"],
    crossSell: ["electrolyseur-sel", "pac-piscine", "eclairage-led-rgb"],
    badge: "Luxe",
  },
  {
    id: "couloir-de-nage",
    category: "piscine",
    name: "Couloir de Nage",
    gammeLabel: "4×15, 4×20, 4×25 m — Sport et bien-être",
    shortDescFr: "Couloir de nage long et étroit pour villas sportives — nage à contre-courant en option.",
    image: SERVICES_IMAGES.poolCouloir,
    specs: [
      { label: "Dimensions", value: "4×15 / 4×20 / 4×25 m" },
      { label: "Nage à contre-courant", value: "Option" },
      { label: "Délais", value: "10 - 14 semaines" },
    ],
    highlights: ["Sport quotidien", "Contre-courant en option"],
    crossSell: ["pac-piscine", "electrolyseur-sel"],
  },
  {
    id: "piscine-naturelle-lagon",
    category: "piscine",
    name: "Piscine Naturelle / Lagon",
    gammeLabel: "Forme libre — Plage immergée — Bio-filtration option",
    shortDescFr: "Piscine lagon avec plage immergée et formes organiques — l'esprit oasis dans votre villa.",
    image: SERVICES_IMAGES.poolLagon,
    specs: [
      { label: "Style", value: "Lagon / Forme libre" },
      { label: "Plage immergée", value: "Incluse" },
      { label: "Bio-filtration", value: "Option" },
    ],
    highlights: ["Plage immergée", "Forme libre", "Esprit oasis"],
    crossSell: ["electrolyseur-sel", "eclairage-led-rgb"],
  },
  {
    id: "spa-jacuzzi",
    category: "piscine",
    name: "Spa & Jacuzzi Intégré",
    gammeLabel: "Spa débordant intégré au pool deck",
    shortDescFr: "Spa jacuzzi intégré à la piscine principale, hydrojets, chromothérapie LED.",
    image: SERVICES_IMAGES.poolSpa,
    specs: [
      { label: "Capacité", value: "4 - 8 personnes" },
      { label: "Jets", value: "Hydromassants" },
      { label: "LED", value: "Chromothérapie" },
    ],
    highlights: ["Hydrojets", "LED chromothérapie", "Intégré pool deck"],
    crossSell: ["piscine-debordement", "pac-piscine"],
  },
  // ========== POMPES PISCINE ==========
  {
    id: "pompe-astralpool-victoria-plus",
    category: "piscine",
    name: "Pompe Astralpool Victoria Plus",
    gammeLabel: "Pompe auto-amorçante haute performance — 0.5 à 3 CV",
    shortDescFr: "Pompe piscine Astralpool Victoria Plus — silencieuse, auto-amorçante, panier de 5L, inox 316.",
    longDescFr:
      "La Victoria Plus est la pompe phare d'Astralpool pour les piscines résidentielles et semi-commerciales. Auto-amorçante avec un panier de pré-filtre de 5 litres, moteur IP-55 avec supports anti-vibrations pour un fonctionnement silencieux (61-70 dBA). Pièces en contact avec l'eau en inox AISI-316. Disponible de 0.5 à 3 CV en monophasé et triphasé.",
    image: "/img/products/piscine/pompes/astralpool/victoria-plus.jpg",
    gallery: ["/img/products/piscine/pompes/astralpool/victoria-plus-installed.jpg"],
    capacities: ["0.5 CV", "0.75 CV", "1 CV", "1.5 CV", "2 CV", "3 CV"],
    specs: [
      { label: "Catégorie", value: "Pompe piscine" },
      { label: "Marque", value: "Astralpool" },
      { label: "Modèle", value: "Victoria Plus NG" },
      { label: "Type", value: "Auto-amorçante centrifuge" },
      { label: "Puissance", value: "0.5 à 3 CV" },
      { label: "Phase", value: "Monophasé / Triphasé" },
      { label: "Pré-filtre", value: "5 litres" },
      { label: "Bruit", value: "61 - 70 dBA" },
      { label: "Protection moteur", value: "IP-55" },
      { label: "Matériaux", value: "Inox AISI-316" },
    ],
    highlights: ["Silencieuse", "Panier 5L", "Inox 316"],
    crossSell: ["pompe-astralpool-sena", "piscine-skimmer-classique", "electrolyseur-sel"],
  },
  {
    id: "pompe-astralpool-sena",
    category: "piscine",
    name: "Pompe Astralpool Sena",
    gammeLabel: "Pompe compacte résidentielle — 0.33 à 1.25 CV",
    shortDescFr: "Pompe piscine Astralpool Sena — compacte, silencieuse, pré-filtre 2L, idéale petites et moyennes piscines.",
    longDescFr:
      "La Sena est une pompe compacte et efficace conçue par Astralpool pour les piscines résidentielles de petite à moyenne taille. Auto-amorçante avec pré-filtre transparent de 2 litres, supports en caoutchouc pour réduire les vibrations, pièces en inox AISI-316. Idéale pour les piscines jusqu'à 60 m³.",
    image: "/img/products/piscine/pompes/astralpool/sena.jpg",
    gallery: ["/img/products/piscine/pompes/astralpool/sena-installed.jpg"],
    capacities: ["0.33 CV", "0.5 CV", "0.75 CV", "1 CV", "1.25 CV"],
    specs: [
      { label: "Catégorie", value: "Pompe piscine" },
      { label: "Marque", value: "Astralpool" },
      { label: "Modèle", value: "Sena" },
      { label: "Type", value: "Auto-amorçante centrifuge" },
      { label: "Puissance", value: "0.33 à 1.25 CV" },
      { label: "Phase", value: "Monophasé / Triphasé" },
      { label: "Pré-filtre", value: "2 litres" },
      { label: "Volume piscine max", value: "≈ 60 m³" },
      { label: "Matériaux", value: "Inox AISI-316" },
    ],
    highlights: ["Compacte", "Silencieuse", "Petit budget"],
    crossSell: ["pompe-astralpool-victoria-plus", "piscine-skimmer-classique", "eclairage-led-rgb"],
  },
  {
    id: "pompe-astralpool-victoria-silent-vs",
    category: "piscine",
    name: "Astralpool Victoria Plus Silent VS",
    gammeLabel: "Pompe à vitesse variable — Économie d'énergie",
    shortDescFr: "Pompe à vitesse variable Astralpool Victoria Plus Silent — jusqu'à 85% d'économie d'énergie, ultra-silencieuse.",
    longDescFr:
      "La Victoria Plus Silent VS est la pompe premium d'Astralpool à vitesse variable. Écran digital intégré pour régler la vitesse, jusqu'à 85% d'économie d'énergie par rapport à une pompe mono-vitesse. Fonctionnement ultra-silencieux, programmation horaire, compatible domotique piscine. Le choix haut de gamme pour les villas.",
    image: "/img/products/piscine/pompes/astralpool/victoria-silent-vs.jpg",
    gallery: ["/img/products/piscine/pompes/astralpool/victoria-plus-installed.jpg"],
    capacities: ["1 CV", "1.5 CV", "2 CV", "3 CV"],
    specs: [
      { label: "Catégorie", value: "Pompe piscine" },
      { label: "Marque", value: "Astralpool" },
      { label: "Modèle", value: "Victoria Plus Silent VS" },
      { label: "Type", value: "Vitesse variable" },
      { label: "Économie", value: "Jusqu'à 85%" },
      { label: "Bruit", value: "< 45 dBA" },
      { label: "Écran", value: "Digital intégré" },
      { label: "Programmation", value: "Multi-vitesse + horaire" },
    ],
    highlights: ["Vitesse variable", "85% d'économie", "Ultra-silencieuse"],
    crossSell: ["pompe-astralpool-victoria-plus", "astralpool-control-box", "piscine-debordement"],
    badge: "Premium",
  },
  {
    id: "pompe-astralpool-senext-xp",
    category: "piscine",
    name: "Astralpool Senext XP",
    gammeLabel: "Pompe auto-amorçante nouvelle génération",
    shortDescFr: "Pompe Astralpool Senext XP — dernière génération, haute efficacité, design moderne, faible consommation.",
    longDescFr:
      "La Senext XP représente la nouvelle génération de pompes auto-amorçantes Astralpool. Design anthracite moderne, haute efficacité hydraulique, moteur basse consommation, grand panier de pré-filtre. Conçue pour les piscines résidentielles exigeantes en performance et en silence.",
    image: "/img/products/piscine/pompes/astralpool/senext-xp.jpg",
    gallery: ["/img/products/piscine/pompes/astralpool/sena-installed.jpg"],
    capacities: ["0.75 CV", "1 CV", "1.5 CV", "2 CV"],
    specs: [
      { label: "Catégorie", value: "Pompe piscine" },
      { label: "Marque", value: "Astralpool" },
      { label: "Modèle", value: "Senext XP" },
      { label: "Type", value: "Auto-amorçante haute efficacité" },
      { label: "Puissance", value: "0.75 à 2 CV" },
      { label: "Efficacité", value: "IE3 haute performance" },
      { label: "Design", value: "Nouvelle génération" },
    ],
    highlights: ["Nouvelle génération", "Haute efficacité", "Basse consommation"],
    crossSell: ["pompe-astralpool-victoria-silent-vs", "pompe-astralpool-sena", "piscine-skimmer-classique"],
    badge: "Nouveau",
  },
  {
    id: "pompe-astralpool-glass-plus",
    category: "piscine",
    name: "Astralpool Glass Plus",
    gammeLabel: "Pompe avec pré-filtre extra-large transparent",
    shortDescFr: "Pompe Astralpool Glass Plus — pré-filtre extra-large ultra-transparent pour une visibilité et un entretien facile.",
    longDescFr:
      "La Glass Plus se distingue par son pré-filtre surdimensionné en matériau ultra-transparent : vous voyez instantanément le niveau de saleté sans démonter. Corps en bleu marine, moteur robuste, idéale pour les piscines avec beaucoup de débris (feuilles, insectes). Entretien simplifié.",
    image: "/img/products/piscine/pompes/astralpool/glass-plus.jpg",
    gallery: ["/img/products/piscine/pompes/astralpool/victoria-plus-installed.jpg"],
    capacities: ["0.5 CV", "0.75 CV", "1 CV", "1.5 CV", "2 CV"],
    specs: [
      { label: "Catégorie", value: "Pompe piscine" },
      { label: "Marque", value: "Astralpool" },
      { label: "Modèle", value: "Glass Plus" },
      { label: "Type", value: "Auto-amorçante" },
      { label: "Puissance", value: "0.5 à 2 CV" },
      { label: "Pré-filtre", value: "Extra-large transparent" },
      { label: "Matériaux", value: "Inox AISI-316" },
    ],
    highlights: ["Pré-filtre XXL", "Visibilité totale", "Entretien facile"],
    crossSell: ["pompe-astralpool-victoria-plus", "pompe-astralpool-sena", "astralpool-strainer"],
  },
  {
    id: "pompe-astralpool-centrifugal",
    category: "piscine",
    name: "Astralpool Pompe Centrifuge",
    gammeLabel: "Pompe centrifuge industrielle — Piscines commerciales",
    shortDescFr: "Pompe centrifuge Astralpool — usage professionnel, piscines publiques, fontaines et jeux d'eau.",
    longDescFr:
      "La pompe centrifuge Astralpool est conçue pour les applications professionnelles : piscines publiques, hôtels, fontaines, cascades et jeux d'eau. Corps en fonte, brides DN, débits élevés, moteur triphasé industriel. Robustesse et fiabilité pour un usage intensif.",
    image: "/img/products/piscine/pompes/astralpool/centrifugal.jpg",
    gallery: ["/img/products/piscine/pompes/astralpool/victoria-plus-installed.jpg"],
    capacities: ["3 CV", "5.5 CV", "7.5 CV", "10 CV"],
    specs: [
      { label: "Catégorie", value: "Pompe piscine" },
      { label: "Marque", value: "Astralpool" },
      { label: "Modèle", value: "Centrifuge industrielle" },
      { label: "Type", value: "Centrifuge (sans pré-filtre)" },
      { label: "Puissance", value: "3 à 10 CV" },
      { label: "Phase", value: "Triphasé 380V" },
      { label: "Raccords", value: "Brides DN" },
      { label: "Usage", value: "Commercial / public" },
    ],
    highlights: ["Industrielle", "Haut débit", "Fonte robuste"],
    crossSell: ["astralpool-control-box", "pompe-astralpool-victoria-plus", "piscine-debordement"],
  },
  {
    id: "astralpool-control-box",
    category: "piscine",
    name: "Astralpool Coffret de Commande",
    gammeLabel: "Coffret électrique de contrôle pompe piscine",
    shortDescFr: "Coffret de commande Astralpool — programmation horaire, contrôle vitesse, protection moteur intégrée.",
    longDescFr:
      "Le coffret de commande Astralpool permet de piloter votre pompe piscine : programmation horaire, multi-vitesse, protection contre les surtensions et les défauts moteur. Écran LCD, installation murale, compatible avec toutes les pompes Astralpool. Indispensable pour une gestion optimale de la filtration.",
    image: "/img/products/piscine/pompes/astralpool/control-box.jpg",
    specs: [
      { label: "Catégorie", value: "Équipement piscine" },
      { label: "Marque", value: "Astralpool" },
      { label: "Type", value: "Coffret de commande" },
      { label: "Fonctions", value: "Programmation, vitesse, protection" },
      { label: "Écran", value: "LCD" },
      { label: "Montage", value: "Mural" },
      { label: "Protection", value: "Surtension + défaut moteur" },
    ],
    highlights: ["Programmation horaire", "Multi-vitesse", "Protection intégrée"],
    crossSell: ["pompe-astralpool-victoria-silent-vs", "pompe-astralpool-victoria-plus", "pompe-astralpool-centrifugal"],
  },
  {
    id: "astralpool-strainer",
    category: "piscine",
    name: "Astralpool Pré-filtre en Ligne",
    gammeLabel: "Pré-filtre transparent en ligne — Protection pompe",
    shortDescFr: "Pré-filtre en ligne Astralpool — protège la pompe des débris, couvercle transparent, entretien facile.",
    longDescFr:
      "Le pré-filtre en ligne Astralpool s'installe avant la pompe pour capturer les gros débris (feuilles, cailloux, insectes) et protéger la turbine. Corps transparent pour un contrôle visuel instantané, panier amovible, raccords union pour un démontage facile. Prolonge la durée de vie de votre pompe.",
    image: "/img/products/piscine/pompes/astralpool/strainer.jpg",
    specs: [
      { label: "Catégorie", value: "Équipement piscine" },
      { label: "Marque", value: "Astralpool" },
      { label: "Type", value: "Pré-filtre en ligne" },
      { label: "Corps", value: "Transparent polycarbonate" },
      { label: "Raccords", value: "Union démontable" },
      { label: "Entretien", value: "Panier amovible" },
    ],
    highlights: ["Transparent", "Protège la pompe", "Entretien facile"],
    crossSell: ["pompe-astralpool-victoria-plus", "pompe-astralpool-glass-plus", "pompe-astralpool-sena"],
  },
  {
    id: "pompe-waterpool-orion",
    category: "piscine",
    name: "Pompe Waterpool Orion",
    gammeLabel: "Pompe auto-amorçante robuste — 0.5 à 3 CV",
    shortDescFr: "Pompe piscine Waterpool Orion — robuste, auto-amorçante, excellent rapport qualité-prix, mono et triphasé.",
    longDescFr:
      "La Waterpool Orion est une pompe auto-amorçante robuste pour piscines résidentielles. Disponible de 0.5 à 3 CV en versions 220V (monophasé) et 380V (triphasé). Pré-filtre avec couvercle transparent, construction durable, idéale pour les piscines au Maroc. Excellent rapport qualité-prix.",
    image: "/img/products/piscine/pompes/waterpool/orion.jpg",
    gallery: ["/img/products/piscine/pompes/waterpool/orion-installed.jpg"],
    capacities: ["0.5 CV", "0.75 CV", "1 CV", "1.5 CV", "2 CV", "3 CV"],
    specs: [
      { label: "Catégorie", value: "Pompe piscine" },
      { label: "Marque", value: "Waterpool" },
      { label: "Modèle", value: "Orion" },
      { label: "Type", value: "Auto-amorçante centrifuge" },
      { label: "Puissance", value: "0.5 à 3 CV" },
      { label: "Alimentation", value: "220V mono / 380V tri" },
      { label: "Pré-filtre", value: "Couvercle transparent" },
    ],
    highlights: ["Robuste", "Mono & Triphasé", "Qualité-prix"],
    crossSell: ["pompe-waterpool-niagara", "waterpool-filtre-sable", "waterpool-groupe-filtration"],
  },
  {
    id: "pompe-waterpool-niagara",
    category: "piscine",
    name: "Pompe Waterpool Niagara",
    gammeLabel: "Pompe haute puissance — 0.75 à 3 CV",
    shortDescFr: "Pompe piscine Waterpool Niagara — haute puissance, compatible eau salée, AISI 316L, pour grands bassins.",
    longDescFr:
      "La Waterpool Niagara est une pompe auto-amorçante haute puissance conçue pour les grands bassins résidentiels et semi-collectifs. Arbre en inox AISI 316L compatible traitement au sel, moteur résiné, girante en Noryl renforcé fibre de verre. Ultra-robuste et silencieuse, elle offre des débits élevés pour une filtration optimale.",
    image: "/img/products/piscine/pompes/waterpool/niagara.jpg",
    gallery: ["/img/products/piscine/pompes/waterpool/orion-installed.jpg"],
    capacities: ["0.75 CV", "1 CV", "1.5 CV", "2 CV", "3 CV"],
    specs: [
      { label: "Catégorie", value: "Pompe piscine" },
      { label: "Marque", value: "Waterpool" },
      { label: "Modèle", value: "Niagara" },
      { label: "Type", value: "Auto-amorçante haute puissance" },
      { label: "Puissance", value: "0.75 à 3 CV" },
      { label: "Arbre", value: "Inox AISI 316L (eau salée)" },
      { label: "Girante", value: "Noryl + fibre de verre" },
      { label: "Pré-filtre", value: "4.5 litres" },
      { label: "Régime", value: "2 900 tr/min" },
    ],
    highlights: ["Haute puissance", "Compatible sel", "Inox 316L"],
    crossSell: ["pompe-waterpool-orion", "waterpool-filtre-sable", "piscine-debordement"],
  },
  {
    id: "waterpool-filtre-sable",
    category: "piscine",
    name: "Waterpool Filtre à Sable",
    gammeLabel: "Filtre à sable — Vanne 6 voies — Ø400 à Ø700",
    shortDescFr: "Filtre à sable Waterpool — vanne multivoie 6 positions, manomètre, pour piscines de 20 à 80 m³.",
    longDescFr:
      "Le filtre à sable Waterpool assure une filtration efficace de votre piscine. Cuve en polyéthylène haute densité résistant aux UV, vanne multivoie 6 positions (filtration, lavage, rinçage, circulation, vidange, fermé), manomètre de pression intégré. Disponible en diamètres 400, 500, 600 et 700 mm pour piscines de 20 à 80 m³.",
    image: "/img/products/piscine/pompes/waterpool/filtre-sable.jpg",
    capacities: ["Ø400 (20-35 m³)", "Ø500 (35-50 m³)", "Ø600 (50-65 m³)", "Ø700 (65-80 m³)"],
    specs: [
      { label: "Catégorie", value: "Filtration piscine" },
      { label: "Marque", value: "Waterpool" },
      { label: "Type", value: "Filtre à sable" },
      { label: "Vanne", value: "Multivoie 6 positions" },
      { label: "Cuve", value: "Polyéthylène anti-UV" },
      { label: "Pression max", value: "2.5 bar" },
      { label: "Média filtrant", value: "Sable ou verre" },
    ],
    highlights: ["6 positions", "Anti-UV", "20 à 80 m³"],
    crossSell: ["pompe-waterpool-orion", "waterpool-groupe-filtration", "waterpool-electrolyseur"],
  },
  {
    id: "waterpool-electrolyseur",
    category: "piscine",
    name: "Waterpool Électrolyseur au Sel",
    gammeLabel: "Traitement automatique au sel — Chlore naturel",
    shortDescFr: "Électrolyseur au sel Waterpool — traitement automatique, cellule titane, écran LCD, eau douce et saine.",
    longDescFr:
      "L'électrolyseur au sel Waterpool produit du chlore naturel à partir du sel dissous dans l'eau. Plus de manipulation de produits chimiques, une eau douce et agréable pour la peau. Cellule en titane autonettoyante, écran LCD, détection automatique du débit et du niveau de sel. Compatible avec les pompes Waterpool.",
    image: "/img/products/piscine/pompes/waterpool/electrolyseur.jpg",
    capacities: ["Jusqu'à 60 m³", "Jusqu'à 90 m³", "Jusqu'à 120 m³"],
    specs: [
      { label: "Catégorie", value: "Traitement piscine" },
      { label: "Marque", value: "Waterpool" },
      { label: "Type", value: "Électrolyseur au sel" },
      { label: "Cellule", value: "Titane autonettoyante" },
      { label: "Écran", value: "LCD" },
      { label: "Détection", value: "Débit + sel automatique" },
      { label: "Salinité", value: "3-5 g/L" },
    ],
    highlights: ["Chlore naturel", "Autonettoyant", "Eau douce"],
    crossSell: ["waterpool-filtre-sable", "pompe-waterpool-orion", "waterpool-groupe-filtration"],
  },
  {
    id: "waterpool-groupe-filtration",
    category: "piscine",
    name: "Waterpool Groupe de Filtration",
    gammeLabel: "Pompe + Filtre complet — Solution clé-en-main",
    shortDescFr: "Groupe de filtration complet Waterpool — pompe Orion + filtre à sable montés sur embase, prêt à installer.",
    longDescFr:
      "Le groupe de filtration Waterpool est une solution clé-en-main : pompe Orion et filtre à sable pré-assemblés sur une embase compacte, raccordés en usine. Installation rapide, encombrement réduit, idéal pour les locaux techniques de petite taille. Vanne 6 voies, manomètre intégré.",
    image: "/img/products/piscine/pompes/waterpool/groupe-filtration.jpg",
    capacities: ["Ø400 + 0.5 CV", "Ø500 + 0.75 CV", "Ø600 + 1 CV", "Ø700 + 1.5 CV"],
    specs: [
      { label: "Catégorie", value: "Filtration piscine" },
      { label: "Marque", value: "Waterpool" },
      { label: "Type", value: "Groupe de filtration complet" },
      { label: "Pompe", value: "Orion (auto-amorçante)" },
      { label: "Filtre", value: "Sable avec vanne 6 voies" },
      { label: "Montage", value: "Pré-assemblé sur embase" },
      { label: "Installation", value: "Plug & Play" },
    ],
    highlights: ["Clé-en-main", "Pré-assemblé", "Compact"],
    crossSell: ["pompe-waterpool-orion", "waterpool-filtre-sable", "waterpool-electrolyseur"],
    badge: "Pack Complet",
  },
  // ========== RENOVATION ==========
  {
    id: "renovation-villa-complete",
    category: "renovation",
    name: "Rénovation Complète de Villa",
    gammeLabel: "Clé-en-main — Un seul interlocuteur",
    shortDescFr: "Rénovation totale de villa, tous corps de métier coordonnés — délais respectés et budget maîtrisé.",
    longDescFr:
      "RIZAL orchestre la rénovation totale de votre villa avec une exigence de finition irréprochable. Un seul interlocuteur, un seul chantier, un seul calendrier. Nos corps de métier — gros œuvre, électricité, plomberie, climatisation, marbrerie, menuiserie aluminium et bois noble, tadelakt, zellige, peinture décorative — interviennent sous coordination unique. Délais respectés et budget maîtrisé, contractualisés dès la signature.",
    image: SERVICES_IMAGES.renovation,
    specs: [
      { label: "Lots couverts", value: "Tous corps de métier" },
      { label: "Coordination", value: "Chef de projet dédié RIZAL" },
      { label: "Engagement", value: "Délais & budget contractualisés" },
      { label: "Garantie", value: "Décennale gros œuvre + biennale finitions" },
    ],
    highlights: ["Un seul interlocuteur", "Délais respectés", "Garantie décennale"],
    crossSell: ["ingelec-cassette-inverter", "onduleur-solax-x3-neo", "adoucisseur-villa", "piscine-debordement"],
    badge: "Service Phare",
  },
  {
    id: "renovation-cuisine",
    category: "renovation",
    name: "Cuisine Équipée Sur Mesure",
    gammeLabel: "Cuisine premium — Marbre, électroménager haut de gamme",
    shortDescFr: "Conception et installation de cuisines sur mesure, plans en marbre, électroménager intégré premium.",
    image: SERVICES_IMAGES.cuisine,
    specs: [
      { label: "Plan de travail", value: "Marbre / Granit / Quartz" },
      { label: "Façades", value: "Bois noble, laqué mat, verre" },
      { label: "Électroménager", value: "Bosch, Siemens, Miele, Liebherr" },
    ],
    highlights: ["Sur-mesure", "Marbre premium", "Électroménager intégré"],
    crossSell: ["renovation-villa-complete", "renovation-marbre"],
  },
  {
    id: "renovation-marbre",
    category: "renovation",
    name: "Marbrerie & Tadelakt",
    gammeLabel: "Marbre, granit, tadelakt, zellige — Savoir-faire marocain",
    shortDescFr: "Pose de marbre, granit, tadelakt traditionnel et zellige — artisans qualifiés.",
    image: SERVICES_IMAGES.marbre,
    specs: [
      { label: "Matières", value: "Marbre, granit, onyx, travertin" },
      { label: "Tadelakt", value: "Traditionnel chaux + savon noir" },
      { label: "Zellige", value: "Authentique de Fès" },
    ],
    highlights: ["Tadelakt traditionnel", "Zellige de Fès", "Marbre premium"],
    crossSell: ["renovation-villa-complete", "renovation-cuisine"],
  },
  {
    id: "domotique-villa",
    category: "renovation",
    name: "Domotique Villa (KNX / Loxone)",
    gammeLabel: "Pilotage centralisé — Éclairage, climat, sécurité, multimédia",
    shortDescFr: "Domotique KNX ou Loxone : éclairage, volets, climatisation, sécurité et multimédia centralisés.",
    image: SERVICES_IMAGES.domotique,
    specs: [
      { label: "Standards", value: "KNX / Loxone" },
      { label: "Pilotage", value: "Tactile mural + smartphone" },
      { label: "Intégration", value: "Climatisation, volets, sons, sécurité" },
    ],
    highlights: ["KNX / Loxone", "Smartphone", "Tout pilotable"],
    crossSell: ["renovation-villa-complete", "lg-multi-v-5"],
  },
  // ========== TRAITEMENT D'EAU ==========
  {
    id: "adoucisseur-villa",
    category: "traitement-eau",
    name: "Adoucisseur d'Eau Villa",
    gammeLabel: "20, 30, 50 L de résine — Anti-calcaire global",
    shortDescFr: "Adoucisseur volumétrique pour villa entière — fini le calcaire à Essaouira.",
    longDescFr:
      "Adoucisseur d'eau volumétrique haut de gamme, capacité 20, 30 ou 50 L de résine selon la taille de la villa. Élimine 99 % du calcaire, protège chaudière, climatiseurs, robinetterie, machine à laver. Régénération automatique. Idéal pour Essaouira où l'eau est très calcaire.",
    image: SERVICES_IMAGES.adoucisseur,
    capacities: ["20 L", "30 L", "50 L"],
    specs: [
      { label: "Type", value: "Volumétrique automatique" },
      { label: "Capacité résine", value: "20 / 30 / 50 L" },
      { label: "Élimination calcaire", value: "99 %" },
      { label: "Régénération", value: "Automatique" },
    ],
    highlights: ["Anti-calcaire 99 %", "Auto-régénérant", "3 capacités"],
    crossSell: ["osmoseur-domestique-6etages", "lampe-uv-sterilisation", "renovation-villa-complete"],
  },
  {
    id: "osmoseur-domestique-6etages",
    category: "traitement-eau",
    name: "Osmoseur Domestique 6 Étages",
    gammeLabel: "Sous évier — Eau pure au robinet",
    shortDescFr: "Osmoseur 6 étages sous évier — eau de boisson pure, débarrassée de 99 % des contaminants.",
    image: SERVICES_IMAGES.osmoseur,
    specs: [
      { label: "Étages filtration", value: "6 (sédiments, charbon, RO, post-carbon, UV, minéralisateur)" },
      { label: "Production", value: "200 L / jour" },
      { label: "Réservoir", value: "12 L sous pression" },
    ],
    highlights: ["6 étages", "Eau pure 99 %", "Sous évier"],
    crossSell: ["adoucisseur-villa", "lampe-uv-sterilisation"],
  },
  {
    id: "osmose-inverse-villa",
    category: "traitement-eau",
    name: "Osmose Inverse Villa Complète",
    gammeLabel: "200 - 500 L/h — Toute la maison",
    shortDescFr: "Système d'osmose inverse villa complète — toute la maison alimentée en eau pure.",
    image: SERVICES_IMAGES.osmoseVilla,
    capacities: ["200 L/h", "300 L/h", "500 L/h"],
    specs: [
      { label: "Production", value: "200 - 500 L / heure" },
      { label: "Application", value: "Villa entière" },
      { label: "Maintenance", value: "Annuelle (incluse en contrat)" },
    ],
    highlights: ["Villa complète", "Production continue", "Contrat maintenance"],
    crossSell: ["adoucisseur-villa", "lampe-uv-sterilisation"],
    badge: "Villa Premium",
  },
  {
    id: "lampe-uv-sterilisation",
    category: "traitement-eau",
    name: "Stérilisation UV In-Line",
    gammeLabel: "Élimination bactéries / virus sans produits chimiques",
    shortDescFr: "Stérilisation UV en ligne — élimine 99,99 % des bactéries et virus sans aucun produit chimique.",
    image: SERVICES_IMAGES.lampeUv,
    specs: [
      { label: "Technologie", value: "UV-C 254 nm" },
      { label: "Efficacité", value: "99,99 % bactéries/virus" },
      { label: "Sans produit chimique", value: "Oui" },
    ],
    highlights: ["Sans chimie", "99,99 % efficace", "Compact"],
    crossSell: ["osmoseur-domestique-6etages", "adoucisseur-villa"],
  },
];
