import type { CatalogItem } from "@/types/catalog";

const PANELS = "/img/solaire/panels";

const SOLAIRE_IMAGES = {
  panneauJinko: `${PANELS}/jinko-tiger-neo-panel.svg`,
  panneauJa: `${PANELS}/ja-solar-panel.svg`,
  panneauTrina: `${PANELS}/trina-vertex-panel.svg`,
  panneauCanadian: `${PANELS}/canadian-solar-panel.svg`,
  panneau: "/img/products/lg/lg-multi-v-5-hero-essaouira.jpg",
  panneauAlt: "/img/products/trane/trane-split-morocco-modern.jpg",
  chauffeEau: "/img/solaire/thermique/from-pdf/lato-teliko-a4-en/lato-teliko-a4-en-p01-img001.jpg",
  logoLato: "/img/brands/solaire/logo-lato-official.png",
} as const;

const ONDULEUR_IMAGES = {
  solaxX1Lite: "/img/products/solaire/onduleurs/solax-x1-lite-lv.jpg",
  solaxX1LiteInstalled: "/img/products/solaire/onduleurs/solax-x1-lite-installed.jpg",
  solis: "/img/products/solaire/onduleurs/solis-triphasé.jpg",
  solisInstalled: "/img/products/solaire/onduleurs/solis-triphase-installed.jpg",
  solaxX3Neo: "/img/products/solaire/onduleurs/solax-x3-neo-lv.jpg",
  solaxX3NeoInstalled: "/img/products/solaire/onduleurs/solax-x3-neo-installed.jpg",
  deye: "/img/products/solaire/onduleurs/deye-hybride.jpg",
  deyeInstalled: "/img/products/solaire/onduleurs/deye-hybride-installed.jpg",
} as const;

const BATTERIE_IMAGES = {
  dynessDL5Mural: "/img/products/solaire/batteries/dyness-dl5-mural.jpg",
  dynessDL5MuralInstalled: "/img/products/solaire/batteries/dyness-dl5-mural-installed.jpg",
  dynessPowerbrick: "/img/products/solaire/batteries/dyness-powerbrick.jpg",
  dynessPowerbrickInstalled: "/img/products/solaire/batteries/dyness-powerbrick-installed.jpg",
  dynessDL5Rack: "/img/products/solaire/batteries/dyness-dl5-rack.jpg",
  dynessDL5RackInstalled: "/img/products/solaire/batteries/dyness-dl5-rack-installed.jpg",
  mustLifepo4: "/img/products/solaire/batteries/must-lp16-lifepo4.jpg",
  mustLifepo4Installed: "/img/products/solaire/batteries/must-lifepo4-installed.jpg",
  elitecEL10: "/img/products/solaire/batteries/elitec-el10.jpg",
  elitecEL10Installed: "/img/products/solaire/batteries/elitec-el10-installed.jpg",
  dyness15kwh: "/img/products/solaire/batteries/dyness-15kwh-tour.jpg",
  dyness15kwhInstalled: "/img/products/solaire/batteries/dyness-15kwh-installed.jpg",
} as const;

export const solaireItems: CatalogItem[] = [
  {
    id: "panneau-jinko-tiger-neo",
    category: "solaire",
    name: "Panneau Solaire Jinko Tiger Neo",
    gammeLabel: "Panneau photovoltaïque — N-Type TOPCon",
    shortDescFr:
      "Panneau Jinko Tiger Neo 500–620 Wc, cellules N-Type TOPCon, haut rendement pour villas au Maroc.",
    longDescFr:
      "La série Jinko Tiger Neo utilise des cellules N-Type TOPCon (HOT 3.0) pour un rendement jusqu'à 23 %, une excellente performance en température élevée et une dégradation minimale. Référence Tier 1 mondiale, disponible de 500 à 620 Wc selon votre toiture.",
    image: SOLAIRE_IMAGES.panneauJinko,
    capacities: ["500 Wc", "550 Wc", "580 Wc", "600 Wc", "620 Wc"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Panneau photovoltaïque" },
      { label: "Marque", value: "Jinko Solar" },
      { label: "Référence", value: "Tiger Neo N-Type TOPCon" },
      { label: "Puissance", value: "500 – 620 Wc" },
      { label: "Technologie", value: "Monocristallin N-Type TOPCon" },
      { label: "Rendement", value: "Jusqu'à 23 %" },
      { label: "Garantie produit", value: "12 ans" },
      { label: "Garantie production", value: "25 ans" },
      { label: "Convient pour", value: "Villa, toiture terrasse, autoconsommation" },
    ],
    highlights: ["Tier 1 n°1 mondial", "500–620 Wc", "25 ans garantie production"],
    crossSell: ["onduleur-solax-x3-neo", "batterie-dyness-dl5", "kit-fixation-toiture"],
    badge: "Tier 1",
  },
  {
    id: "panneau-ja-solar-deepblue",
    category: "solaire",
    name: "Panneau Solaire JA Solar DeepBlue",
    gammeLabel: "Panneau photovoltaïque — DeepBlue 4.0 Pro",
    shortDescFr:
      "Panneau JA Solar DeepBlue 4.0 Pro 500–600 Wc, monocristallin haute efficacité, Tier 1.",
    longDescFr:
      "JA Solar DeepBlue 4.0 Pro combine cellules monocristallines PERC/TOPCon et faible coefficient de température. Gamme 500 à 600 Wc, idéale pour les installations résidentielles et tertiaires à Essaouira. Garantie produit 12 ans, production 25 ans.",
    image: SOLAIRE_IMAGES.panneauJa,
    capacities: ["500 Wc", "540 Wc", "560 Wc", "580 Wc", "600 Wc"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Panneau photovoltaïque" },
      { label: "Marque", value: "JA Solar" },
      { label: "Référence", value: "DeepBlue 4.0 Pro" },
      { label: "Puissance", value: "500 – 600 Wc" },
      { label: "Technologie", value: "Monocristallin PERC / TOPCon" },
      { label: "Rendement", value: "Jusqu'à 22,5 %" },
      { label: "Garantie produit", value: "12 ans" },
      { label: "Garantie production", value: "25 ans" },
      { label: "Convient pour", value: "Villa, autoconsommation, toiture inclinée" },
    ],
    highlights: ["Tier 1", "500–600 Wc", "DeepBlue 4.0"],
    crossSell: ["onduleur-solax-x1-lite", "batterie-dyness-dl5", "kit-fixation-toiture"],
    badge: "Tier 1",
  },
  {
    id: "panneau-trina-vertex",
    category: "solaire",
    name: "Panneau Solaire Trina Vertex S+",
    gammeLabel: "Panneau photovoltaïque — Vertex S+",
    shortDescFr:
      "Panneau Trina Solar Vertex S+ 500–700 Wc, haute puissance compacte pour maximiser la production.",
    longDescFr:
      "Trina Solar Vertex S+ offre une puissance record jusqu'à 700 Wc dans un format optimisé. Technologie multi-busbar, excellent rendement en faible luminosité. Solution Tier 1 pour villas à forte consommation ou toitures limitées en surface.",
    image: SOLAIRE_IMAGES.panneauTrina,
    capacities: ["500 Wc", "550 Wc", "600 Wc", "650 Wc", "670 Wc", "700 Wc"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Panneau photovoltaïque" },
      { label: "Marque", value: "Trina Solar" },
      { label: "Référence", value: "Vertex S+" },
      { label: "Puissance", value: "500 – 700 Wc" },
      { label: "Technologie", value: "Monocristallin TOPCon" },
      { label: "Rendement", value: "Jusqu'à 22,8 %" },
      { label: "Garantie produit", value: "12 ans" },
      { label: "Garantie production", value: "25 ans" },
      { label: "Convient pour", value: "Villa premium, forte consommation, toiture compacte" },
    ],
    highlights: ["Jusqu'à 700 Wc", "Vertex S+", "Tier 1"],
    crossSell: ["onduleur-solax-x3-neo", "batterie-dyness-15kwh", "kit-fixation-toiture"],
    badge: "700 Wc max",
  },
  {
    id: "panneau-canadian-solar",
    category: "solaire",
    name: "Panneau Solaire Canadian Solar",
    gammeLabel: "Panneau photovoltaïque — TOPHiKu6 / HiHero",
    shortDescFr:
      "Panneau Canadian Solar 500–665 Wc, TOPCon all-black, fiabilité et esthétique premium.",
    longDescFr:
      "Canadian Solar TOPHiKu6 et HiHero allient technologie TOPCon et design full-black pour une intégration discrète sur toiture. Puissances de 500 à 665 Wc, garantie produit 15 ans et production 30 ans — choix premium pour villas haut de gamme.",
    image: SOLAIRE_IMAGES.panneauCanadian,
    capacities: ["500 Wc", "540 Wc", "580 Wc", "620 Wc", "665 Wc"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Panneau photovoltaïque" },
      { label: "Marque", value: "Canadian Solar" },
      { label: "Référence", value: "TOPHiKu6 / HiHero" },
      { label: "Puissance", value: "500 – 665 Wc" },
      { label: "Technologie", value: "Monocristallin TOPCon all-black" },
      { label: "Rendement", value: "Jusqu'à 22,9 %" },
      { label: "Garantie produit", value: "15 ans" },
      { label: "Garantie production", value: "30 ans" },
      { label: "Convient pour", value: "Villa premium, toiture visible, esthétique soignée" },
    ],
    highlights: ["All-black disponible", "500–665 Wc", "Garantie 30 ans"],
    crossSell: ["onduleur-solis-triphase", "batterie-dyness-dl5", "kit-fixation-toiture"],
    badge: "Premium",
  },
  {
    id: "panneau-longi-himo-6",
    category: "solaire",
    name: "Panneau Solaire LONGi Hi-MO 6",
    gammeLabel: "Panneau photovoltaïque — HPBC haute performance",
    shortDescFr:
      "Panneau LONGi Hi-MO 6 à cellules HPBC, excellent rendement et esthétique full-black selon disponibilité.",
    longDescFr:
      "LONGi Hi-MO 6 est une gamme premium pour les toitures de villas : cellules HPBC haute performance, design soigné, production stable et excellent comportement en faible luminosité. Recommandé lorsque l'esthétique de la toiture et la performance longue durée sont prioritaires.",
    image: SOLAIRE_IMAGES.panneauAlt,
    capacities: ["435 Wc", "500 Wc", "550 Wc"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Panneau photovoltaïque" },
      { label: "Marque", value: "LONGi" },
      { label: "Référence", value: "Hi-MO 6 HPBC" },
      { label: "Technologie", value: "Monocristallin HPBC" },
      { label: "Garantie produit", value: "12 ans" },
      { label: "Garantie production", value: "25 ans" },
      { label: "Convient pour", value: "Villa premium, toiture visible, projet esthétique" },
    ],
    highlights: ["Design premium", "HPBC haute performance", "Production stable"],
    crossSell: ["onduleur-solax-x1-lite", "batterie-dyness-dl5"],
    badge: "Premium",
  },
  // ========== ONDULEURS ==========
  {
    id: "onduleur-solax-x1-lite",
    category: "solaire",
    name: "Onduleur SolaX X1-LITE LV",
    gammeLabel: "Onduleur hybride monophasé — Low Voltage",
    shortDescFr: "Onduleur hybride monophasé SolaX X1-LITE LV — compact, silencieux, compatible batteries basse tension.",
    longDescFr:
      "Le SolaX X1-LITE LV est un onduleur hybride monophasé conçu pour les installations résidentielles. Design compact, écran LED intuitif, monitoring via app SolaX Cloud, compatible batteries lithium basse tension. Idéal pour les villas au Maroc en autoconsommation avec stockage.",
    image: ONDULEUR_IMAGES.solaxX1Lite,
    gallery: [ONDULEUR_IMAGES.solaxX1LiteInstalled],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Onduleur hybride" },
      { label: "Marque", value: "SolaX Power" },
      { label: "Référence", value: "X1-LITE LV" },
      { label: "Phase", value: "Monophasé" },
      { label: "Compatibilité batterie", value: "Lithium basse tension (LV)" },
      { label: "Monitoring", value: "SolaX Cloud (app + web)" },
      { label: "Garantie", value: "5 ans (extensible 10 ans)" },
    ],
    highlights: ["Monophasé hybride", "Compact et silencieux", "App SolaX Cloud"],
    crossSell: ["batterie-dyness-dl5", "onduleur-solax-x3-neo", "panneau-jinko-tiger-neo"],
  },
  {
    id: "onduleur-solis-triphase",
    category: "solaire",
    name: "Onduleur Solis Triphasé",
    gammeLabel: "Onduleur triphasé — Grandes installations",
    shortDescFr: "Onduleur triphasé Solis — haute puissance pour villas et projets commerciaux au Maroc.",
    longDescFr:
      "Solis est un leader mondial des onduleurs solaires. Ce modèle triphasé est conçu pour les installations de grande envergure : villas avec forte consommation, commerces, bâtiments tertiaires. Écran LCD, multiples MPPT, rendement > 98 %, monitoring Solis Cloud.",
    image: ONDULEUR_IMAGES.solis,
    gallery: [ONDULEUR_IMAGES.solisInstalled],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Onduleur réseau" },
      { label: "Marque", value: "Solis (Ginlong)" },
      { label: "Phase", value: "Triphasé" },
      { label: "Rendement", value: "> 98 %" },
      { label: "MPPT", value: "Multi-tracker" },
      { label: "Monitoring", value: "Solis Cloud" },
      { label: "Garantie", value: "5 ans (extensible)" },
    ],
    highlights: ["Triphasé haute puissance", "Multi-MPPT", "Monitoring cloud"],
    crossSell: ["onduleur-solax-x3-neo", "batterie-dyness-15kwh", "panneau-jinko-tiger-neo"],
  },
  {
    id: "onduleur-solax-x3-neo",
    category: "solaire",
    name: "Onduleur SolaX X3-NEO-LV",
    gammeLabel: "Onduleur hybride triphasé — 10K Low Voltage",
    shortDescFr: "Onduleur hybride triphasé SolaX X3-NEO-LV 10K — puissant, compatible batteries LV, monitoring app.",
    longDescFr:
      "Le SolaX X3-NEO-LV est un onduleur hybride triphasé de nouvelle génération. Il combine injection réseau et stockage batterie pour une autoconsommation maximale. Compatible batteries basse tension, monitoring SolaX Cloud, design compact. Disponible en 5 kW à 15 kW.",
    image: ONDULEUR_IMAGES.solaxX3Neo,
    gallery: [ONDULEUR_IMAGES.solaxX3NeoInstalled],
    capacities: ["5 kW", "8 kW", "10 kW", "12 kW", "15 kW"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Onduleur hybride triphasé" },
      { label: "Marque", value: "SolaX Power" },
      { label: "Référence", value: "X3-NEO-LV" },
      { label: "Phase", value: "Triphasé" },
      { label: "Compatibilité batterie", value: "Lithium basse tension (LV)" },
      { label: "Monitoring", value: "SolaX Cloud" },
      { label: "Garantie", value: "5 ans (extensible 10 ans)" },
    ],
    highlights: ["Triphasé hybride", "5-15 kW", "Stockage + réseau"],
    crossSell: ["onduleur-solax-x1-lite", "batterie-dyness-dl5", "panneau-longi-himo-6"],
    badge: "Nouveau",
  },
  {
    id: "onduleur-deye-hybride",
    category: "solaire",
    name: "Onduleur Deye Hybride",
    gammeLabel: "Onduleur hybride — Monophasé / Triphasé",
    shortDescFr: "Onduleur hybride Deye — solution polyvalente pour autoconsommation et backup avec batteries.",
    longDescFr:
      "Deye propose des onduleurs hybrides fiables et polyvalents. Compatible batteries lithium, fonctionnement en mode hybride (réseau + batteries) ou off-grid. Écran LCD, monitoring par app, protection intégrée. Adapté aux villas marocaines recherchant autonomie et sécurité électrique.",
    image: ONDULEUR_IMAGES.deye,
    gallery: [ONDULEUR_IMAGES.deyeInstalled],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Onduleur hybride" },
      { label: "Marque", value: "Deye" },
      { label: "Phase", value: "Monophasé / Triphasé" },
      { label: "Mode", value: "Hybride + Off-Grid" },
      { label: "Compatibilité batterie", value: "Lithium (48V)" },
      { label: "Monitoring", value: "App Deye Cloud" },
      { label: "Garantie", value: "5 ans" },
    ],
    highlights: ["Hybride + Off-Grid", "Polyvalent", "App de suivi"],
    crossSell: ["batterie-dyness-dl5", "batterie-must-lifepo4", "panneau-jinko-tiger-neo"],
  },
  // ========== BATTERIES ==========
  {
    id: "batterie-dyness-dl5",
    category: "solaire",
    name: "Batterie Dyness DL5.0C",
    gammeLabel: "Batterie LiFePO4 murale — 5.12 kWh",
    shortDescFr: "Batterie Dyness DL5.0C LiFePO4 5.12 kWh — murale, compacte, empilable jusqu'à 60 kWh.",
    longDescFr:
      "La Dyness DL5.0C est une batterie murale LiFePO4 compacte et modulaire. 5.12 kWh par module, empilable jusqu'à 60 kWh, 6 000+ cycles, décharge 1C, IP20, compatible avec la majorité des onduleurs hybrides du marché. Installation simple, monitoring par app.",
    image: BATTERIE_IMAGES.dynessDL5Mural,
    gallery: [BATTERIE_IMAGES.dynessDL5MuralInstalled, BATTERIE_IMAGES.dynessDL5Rack, BATTERIE_IMAGES.dynessDL5RackInstalled],
    capacities: ["5.12 kWh", "10.24 kWh", "15.36 kWh", "Jusqu'à 60 kWh"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Batterie lithium solaire" },
      { label: "Marque", value: "Dyness" },
      { label: "Référence", value: "DL5.0C" },
      { label: "Chimie", value: "LiFePO4" },
      { label: "Capacité module", value: "5.12 kWh" },
      { label: "Tension", value: "51.2 V" },
      { label: "Cycles", value: "6 000+" },
      { label: "Montage", value: "Mural ou rack 19 pouces" },
      { label: "Garantie", value: "10 ans" },
    ],
    highlights: ["LiFePO4 sécurisée", "6 000+ cycles", "Murale ou rack"],
    crossSell: ["onduleur-solax-x1-lite", "batterie-dyness-powerbrick", "panneau-jinko-tiger-neo"],
  },
  {
    id: "batterie-dyness-powerbrick",
    category: "solaire",
    name: "Dyness PowerBrick",
    gammeLabel: "Batterie tour grande capacité — LiFePO4",
    shortDescFr: "Dyness PowerBrick — batterie tour haute capacité LiFePO4, design élégant, pour grandes villas.",
    longDescFr:
      "Le Dyness PowerBrick est une solution de stockage grande capacité au sol. Design élégant type tour, LiFePO4, extensible en parallèle (jusqu'à 50 unités), pas de black-out, auto-chauffage intégré, monitoring intelligent. Conçu pour les grandes villas et résidences prestige au Maroc.",
    image: BATTERIE_IMAGES.dynessPowerbrick,
    gallery: [BATTERIE_IMAGES.dynessPowerbrickInstalled],
    capacities: ["14.3 kWh", "28.6 kWh", "Extensible"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Batterie lithium grande capacité" },
      { label: "Marque", value: "Dyness" },
      { label: "Référence", value: "PowerBrick" },
      { label: "Chimie", value: "LiFePO4" },
      { label: "Expansion", value: "Jusqu'à 50 unités en parallèle" },
      { label: "No Black Out", value: "Oui" },
      { label: "Auto-chauffage", value: "-25°C à 55°C" },
      { label: "Garantie", value: "10 ans" },
    ],
    highlights: ["Grande capacité", "Design élégant", "No Black Out"],
    crossSell: ["onduleur-solax-x3-neo", "batterie-dyness-15kwh", "onduleur-deye-hybride"],
    badge: "Premium",
  },
  {
    id: "batterie-dyness-15kwh",
    category: "solaire",
    name: "Dyness 15 kWh Tour",
    gammeLabel: "Batterie tour 15 kWh — 51.2V 280Ah LiFePO4",
    shortDescFr: "Batterie Dyness 15 kWh LiFePO4 — 8 000 cycles, 10 ans garantie, IP20, idéale grande villa.",
    longDescFr:
      "La batterie tour Dyness 15 kWh est conçue pour les installations résidentielles de grande envergure. LiFePO4 51.2V 280Ah, 8 000 cycles à 95% DoD, garantie 10 ans, IP20, monitoring BMS intégré. Solution fiable pour l'autonomie complète.",
    image: BATTERIE_IMAGES.dyness15kwh,
    gallery: [BATTERIE_IMAGES.dyness15kwhInstalled],
    capacities: ["15 kWh"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Batterie lithium tour" },
      { label: "Marque", value: "Dyness" },
      { label: "Capacité", value: "15 kWh" },
      { label: "Tension", value: "51.2 V" },
      { label: "Courant", value: "280 Ah" },
      { label: "Chimie", value: "LiFePO4" },
      { label: "Cycles", value: "8 000 (95% DoD)" },
      { label: "Garantie", value: "10 ans" },
    ],
    highlights: ["15 kWh", "8 000 cycles", "Garantie 10 ans"],
    crossSell: ["batterie-dyness-powerbrick", "onduleur-solax-x3-neo", "onduleur-solis-triphase"],
    badge: "Grande Capacité",
  },
  {
    id: "batterie-must-lifepo4",
    category: "solaire",
    name: "Batterie MUST LiFePO4 5.1 kWh",
    gammeLabel: "Batterie murale MUST — LP16-48100 LiFePO4",
    shortDescFr: "Batterie MUST LP16-48100 LiFePO4 5.1 kWh — murale, écran LCD, compatible multi-onduleurs.",
    longDescFr:
      "La batterie MUST LP16-48100 est une solution murale LiFePO4 de 5.1 kWh (51.2V / 100Ah). Écran LCD intégré, BMS intelligent, compatible avec la majorité des onduleurs hybrides. Solution fiable et accessible pour l'autoconsommation résidentielle au Maroc.",
    image: BATTERIE_IMAGES.mustLifepo4,
    gallery: [BATTERIE_IMAGES.mustLifepo4Installed],
    capacities: ["5.1 kWh", "10.2 kWh (×2)", "15.3 kWh (×3)"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Batterie lithium murale" },
      { label: "Marque", value: "MUST" },
      { label: "Référence", value: "LP16-48100" },
      { label: "Chimie", value: "LiFePO4" },
      { label: "Capacité", value: "5.1 kWh (51.2V / 100Ah)" },
      { label: "Écran", value: "LCD intégré" },
      { label: "Garantie", value: "5 ans" },
    ],
    highlights: ["LiFePO4 sûre", "Écran LCD", "Prix accessible"],
    crossSell: ["onduleur-deye-hybride", "batterie-dyness-dl5", "panneau-jinko-tiger-neo"],
  },
  {
    id: "batterie-elitec-el10",
    category: "solaire",
    name: "Batterie Elitec-Lithium EL10",
    gammeLabel: "Batterie rack 5.12 kWh — 51.2V 100Ah",
    shortDescFr: "Batterie Elitec-Lithium EL10 — 5.12 kWh rack 19\", LiFePO4, empilable.",
    longDescFr:
      "L'Elitec EL10 est une batterie rack 19 pouces LiFePO4 de 5.12 kWh. Format compact, empilable, BMS intégré, compatible avec les principaux onduleurs du marché. Solution robuste pour installations solaires résidentielles et petits commerces.",
    image: BATTERIE_IMAGES.elitecEL10,
    gallery: [BATTERIE_IMAGES.elitecEL10Installed],
    capacities: ["5.12 kWh", "10.24 kWh (×2)", "15.36 kWh (×3)"],
    specs: [
      { label: "Catégorie", value: "Énergie solaire" },
      { label: "Type", value: "Batterie lithium rack" },
      { label: "Marque", value: "Elitec-Lithium" },
      { label: "Référence", value: "EL10" },
      { label: "Chimie", value: "LiFePO4" },
      { label: "Capacité", value: "5.12 kWh (51.2V / 100Ah)" },
      { label: "Format", value: "Rack 19 pouces" },
      { label: "Garantie", value: "5 ans" },
    ],
    highlights: ["Rack 19\"", "LiFePO4", "Empilable"],
    crossSell: ["batterie-dyness-dl5", "onduleur-solax-x1-lite", "onduleur-solis-triphase"],
  },
];
